import { expect, test } from '@playwright/test'

test('Bauma–Wila opens from the catalog, plays and shares its final observation', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Road recordings', exact: true }).click()
  const choice = page.getByRole('dialog').getByRole('link', { name: /Bauma–Wila/ })
  await expect(choice).toContainText('104 recorded minutes')
  await choice.click()
  const card = page.locator('.cantonal-pilot'), clock = page.locator('.scrubber input')
  await expect(card).toContainText('Bauma–Wila · Tösstalstrasse')
  await expect(card).toContainText('104 complete recorded minutes · no gaps')
  await expect(card).toContainText('Mapped junction areas: 2')
  await expect(clock).toHaveValue('51240')
  await expect(clock).toHaveAttribute('max', '57420')
  await expect(page.locator('.road-corridor-card .metric-grid strong').nth(1)).toHaveText(/≈[1-9]/)
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await clock.inputValue())).toBeGreaterThan(51240)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await page.screenshot({ path: info.outputPath('bauma-wila.png') })
  await clock.fill('57420')
  await page.getByRole('button', { name: 'Share study', exact: true }).click()
  const url = await page.locator('.explore-link').inputValue()
  expect(url).toContain('recording=bauma-wila-2026-09-08')
  await page.goto(url)
  await expect(card).toContainText('Bauma–Wila · Tösstalstrasse')
  await expect(clock).toHaveValue('57420')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await card.getByRole('button', { name: 'Return to morning roads' }).click()
  await expect(clock).toHaveAttribute('min', '24300')
  expect(errors).toEqual([])
})

test('a failed Bauma–Wila download retries at the shared final minute', async ({ page }) => {
  await page.route('**/bauma-wila-road-pilot.json', route => route.fulfill({ status: 503, body: '' }))
  await page.goto('/?recording=bauma-wila-2026-09-08&time=57420')
  await expect(page.locator('.cantonal-pilot')).toContainText('Try again')
  await page.unroute('**/bauma-wila-road-pilot.json')
  await page.getByRole('button', { name: 'Play Bauma–Wila recording' }).click()
  await expect(page.locator('.cantonal-pilot')).toContainText('104 complete recorded minutes')
  await expect(page.locator('.scrubber input')).toHaveValue('57420')
})
