import { expect, test } from '@playwright/test'

test('road recordings are discoverable without fetching playback until selected', async ({ page }, info) => {
  const requests: string[] = []
  page.on('request', request => { if (/road-pilot\.json/.test(request.url())) requests.push(request.url()) })
  await page.goto('/?latitude=47&longitude=8#private')
  const open = page.getByRole('button', { name: 'Road recordings', exact: true })
  await open.click()
  const dialog = page.getByRole('dialog', { name: 'Road recordings', exact: true })
  await expect(dialog.getByRole('link')).toHaveCount(2)
  await expect(dialog).toContainText('40 recorded minutes')
  await expect(dialog).toContainText('Includes observation gaps')
  await expect(dialog).toContainText('104 recorded minutes')
  await expect(dialog).toContainText('No observation gaps')
  expect(requests).toEqual([])
  for (const link of await dialog.getByRole('link').all()) expect(await link.getAttribute('href')).not.toMatch(/latitude|longitude|private/)
  await page.screenshot({ path: info.outputPath('road-recordings.png') })
  await dialog.getByRole('button', { name: 'Close ×', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(open).toBeFocused()
  await open.click()
  await dialog.getByRole('link', { name: /Horgen/ }).click()
  await expect(page.locator('.cantonal-pilot')).toContainText('Horgen · Seestrasse')
  await expect(page.locator('.scrubber input')).toHaveValue('49440')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await open.click()
  await expect(dialog.getByRole('link', { name: /Horgen/ })).toHaveAttribute('aria-current', 'page')
  await dialog.getByRole('link', { name: /Wallisellen–Bassersdorf/ }).click()
  await expect(page.locator('.cantonal-pilot')).toContainText('104 complete recorded minutes')
  await expect(page.locator('.scrubber input')).toHaveValue('51240')
  expect(requests.some(url => url.includes('zurich-cantonal-road-pilot.json'))).toBe(true)
  expect(requests.some(url => url.includes('wallisellen-bassersdorf-road-pilot.json'))).toBe(true)
})

test('Escape closes the recording picker and preserves the current playback time', async ({ page }) => {
  await page.goto('/?recording=horgen-2026-09-08&time=49020')
  await expect(page.locator('.cantonal-pilot')).toContainText('Traffic is hidden')
  const open = page.getByRole('button', { name: 'Road recordings', exact: true })
  await open.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(open).toBeFocused()
  await expect(page.locator('.scrubber input')).toHaveValue('49020')
})
