import {expect, test} from '@playwright/test'
import railway from '../public/data/rochers-day.json' with { type: 'json' }

test('combined Glion journey keeps two vehicles and the interchange on one clock', async ({page, isMobile}, info) => {
 const errors: string[] = [], requests: string[] = []
 page.on('pageerror', e => errors.push(e.message))
 page.on('request', r => requests.push(r.url()))
 await page.goto('/?study=territet&date=2026-09-04')
 await expect(page.getByRole('button', {name: /Continue to Rochers-de-Naye/})).toBeVisible()
 expect(requests.some(r => r.includes('rochers-day.json'))).toBe(false)
 await page.getByRole('button', {name: /Continue to Rochers-de-Naye/}).click()
 const card = page.locator('.glion-journey'), clock = page.locator('.scrubber input')
 await expect(card).toHaveAttribute('data-phase', 'first-leg')
 await expect(clock).toHaveValue('41640')
 if (isMobile) await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await expect(card.getByRole('combobox', {name: 'Choose a departure'}).locator('option')).toHaveCount(10)
 await expect(card.locator('nav button')).toHaveCount(15)
 await expect(card.locator('nav')).not.toContainText('Montreux')
 await card.locator('nav button').filter({hasText: 'Glion (funi)'}).click()
 await expect(clock).toHaveValue('42000')
 await expect(card).toHaveAttribute('data-phase', 'interchange')
 await expect(card.getByRole('status')).toContainText('Until departure 4:00')
 await expect(card).toContainText('Source minimum: 1 minute')
 await page.waitForTimeout(800)
 await page.screenshot({path: info.outputPath('glion-interchange.png')})
 await clock.fill('42230')
 await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'second-leg')
 await page.getByRole('button', {name: /Pause motion/}).click()
 await card.locator('nav button').filter({hasText: 'Caux'}).filter({hasNotText: 'Haut-de-Caux'}).filter({hasNotText: 'Les Echets'}).first().click()
 await expect(clock).toHaveValue('42960')
 await expect(card.locator('nav button[aria-current]')).toContainText('11:56 → 11:58')
 await page.waitForTimeout(800)
 await page.screenshot({path: info.outputPath('glion-railway.png')})
 await clock.fill('44510'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'complete')
 await expect(page.getByRole('button', {name: /Resume motion/})).toBeVisible()
 await card.getByRole('button', {name: /Replay journey/}).click(); await expect(clock).toHaveValue('41640')
 if (isMobile) await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.getByRole('combobox', {name: 'Direction', exact: true}).selectOption('descent')
 await expect(clock).toHaveValue('44820')
 await expect(card.getByRole('heading')).toHaveText('Rochers-de-Naye → Territet')
 await card.locator('.glion-transfer button').click()
 await expect(clock).toHaveValue('47400'); await expect(card).toHaveAttribute('data-phase', 'interchange')
 await expect(card.getByRole('status')).toContainText('Until departure 9:00')
 await card.locator('nav button').filter({hasText: 'Glion (funi)'}).click()
 await expect(clock).toHaveValue('47940'); await expect(card).toHaveAttribute('data-phase', 'second-leg')
 await card.locator('nav button').filter({hasText: 'Territet (funi)'}).click()
 await expect(clock).toHaveValue('48300'); await expect(card).toHaveAttribute('data-phase', 'complete')
 if (isMobile) await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.getByRole('combobox', {name: 'Choose a departure'}).selectOption({index: 0})
 await expect(clock).toHaveValue('34020')
 await card.getByRole('button', {name: 'Exit journey', exact: true}).click()
 await expect(card).toHaveCount(0)
 await page.getByRole('button', {name: /Follow the Territet–Glion funicular/}).click()
 await expect(page.locator('.territet-journey nav button')).toHaveCount(3)
 expect(requests.filter(r => r.includes('rochers-day.json'))).toHaveLength(1)
 expect(requests.some(r => r.includes('rochers-terrain.json'))).toBe(false)
 if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 expect(errors).toEqual([])
})

test('combined Glion journey retries failed and mismatched source data', async ({page}) => {
 let response = 'failed'
 await page.route('**/rochers-day.json', route => response === 'failed' ? route.fulfill({status: 503, body: 'unavailable'}) : response === 'wrong-date' ? route.fulfill({json: {...railway, metadata: {...railway.metadata, serviceDate: '2026-09-05'}}}) : route.continue())
 await page.goto('/?study=territet&date=2026-09-04')
 await page.getByRole('button', {name: /Continue to Rochers-de-Naye/}).click()
 const card = page.locator('.glion-journey')
 await expect(card).toHaveAttribute('data-phase', 'unavailable')
 response = 'wrong-date'; await card.getByRole('button', {name: 'Retry connection', exact: true}).click()
 await expect(card).toHaveAttribute('data-phase', 'unavailable')
 await expect(card.locator('nav')).toHaveCount(0)
 response = 'valid'; await card.getByRole('button', {name: 'Retry connection', exact: true}).click()
 await expect(card).toHaveAttribute('data-phase', 'first-leg')
 await expect(card.locator('nav button')).toHaveCount(15)
})

test('combined Glion links reopen the exact downhill interchange and retain translated controls', async ({page, isMobile}) => {
 await page.goto('/?study=territet&date=2026-09-04&time=47400&glion=.ojp-91-37-F.1.TA.89.j26')
 const card = page.locator('.glion-journey')
 await expect(card).toHaveAttribute('data-direction', 'descent')
 await expect(card).toHaveAttribute('data-phase', 'interchange')
 await expect(page.locator('.scrubber input')).toHaveValue('47400')
 await page.getByRole('button', {name: 'Share study', exact: true}).click()
 const link = page.locator('#study-share input')
 await expect(link).toHaveValue(/glion=\.ojp-91-37-F\.1\.TA\.89\.j26/)
 const url = await link.inputValue()
 await page.goto(url)
 await expect(card).toHaveAttribute('data-phase', 'interchange')
 await expect(page.locator('.scrubber input')).toHaveValue('47400')
 for (const [code, label] of [['DE', 'Umsteigen in Glion'], ['FR', 'Changer à Glion'], ['IT', 'Cambio a Glion']]) {
  if (isMobile) {
   await page.locator('.mobile-language-picker .mobile-picker__trigger').click()
   await page.getByRole('option', {name: new RegExp(`^${code} `)}).click()
  } else await page.locator('.language-picker').getByRole('button', {name: code, exact: true}).click()
  await expect(card.getByRole('status')).toContainText(label)
  await expect(page.locator('.scrubber input')).toHaveValue('47400')
 }
 await page.goto('/?study=territet&date=2026-09-04&glion=.ojp-91-37-F.1.TA.99999.j26')
 await expect(card).toHaveAttribute('data-phase', 'unavailable')
 await expect(card.locator('nav')).toHaveCount(0)
})

test('station inspection leaves the combined guide without losing the railway stop', async ({page}) => {
 await page.goto('/?study=territet&date=2026-09-04&time=47400&glion=.ojp-91-37-F.1.TA.89.j26')
 await expect(page.locator('.glion-journey')).toHaveAttribute('data-phase', 'interchange')
 await page.locator('.train-search input').fill('Caux')
 await page.getByRole('option').filter({has: page.locator('.result-service', {hasText: /^Caux$/})}).click()
 await expect(page.locator('.glion-journey')).toHaveCount(0)
 await expect(page.locator('.station-card .service')).toHaveText('Caux')
 await page.locator('.train-search input').fill('')
 await page.getByRole('button', {name: /Follow the Territet–Glion funicular/}).click()
 await expect(page.locator('.territet-journey nav button')).toHaveCount(3)
})
