import {expect, test} from '@playwright/test'

test('combined terrain preserves funicular, interchange, outdoor and masked phases in both directions', async ({page, isMobile}, info) => {
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
 let requests = 0, funicularRequests = 0; page.on('request', r => {if (r.url().includes('rochers-ascent-terrain.json')) requests++; if (r.url().includes('territet-ascent-terrain.json')) funicularRequests++})
 await page.goto('/?study=territet&date=2026-09-04&glion=.ojp-91-37-F.1.TA.45.j26')
 const funicularScene = page.locator('.territet-terrain-scene')
 const card = page.locator('.glion-journey'), clock = page.locator('.scrubber input'), scene = page.locator('.rochers-terrain-scene'), status = card.locator('[data-terrain-status]')
 await expect(card).toHaveAttribute('data-phase', 'first-leg'); await expect(clock).toHaveValue('41640'); expect(requests).toBe(0); expect(funicularRequests).toBe(0)
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(status).toContainText('Rail and ground heights differ'); await expect(scene).toHaveCount(0)
 await clock.fill('41700'); await expect(funicularScene).toHaveAttribute('data-rendered', 'true'); await expect(funicularScene).toHaveAttribute('data-context-tracks', '2')
 await expect(card.locator('[data-terrain-leg]')).toHaveAttribute('data-terrain-leg', 'funicular'); await expect(card).toContainText('swissALTI3D 2021')
 await page.screenshot({path: info.outputPath('glion-funicular-terrain.png')})
 await clock.fill('41800'); await expect(status).toContainText('Passing loop'); await expect(funicularScene).toHaveCount(0)
 await clock.fill('41990'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'interchange'); await expect(funicularScene).toHaveCount(0)
 await page.getByRole('button', {name: /Pause motion/}).click()
 await clock.fill('42000'); await expect(status).toHaveAttribute('data-terrain-status', 'interchange'); await expect(scene).toHaveCount(0)
 await expect(card).toContainText('Until departure 4:00')
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.locator('nav button').filter({has: page.getByText('Caux', {exact: true})}).click()
 await expect(clock).toHaveValue('42960'); await expect(funicularScene).toHaveCount(0); await expect(card).toContainText('swissALTIRegio'); await expect(scene).toHaveAttribute('data-rendered', 'true'); await expect(scene).toHaveAttribute('data-stopped', 'true')
 await page.screenshot({path: info.outputPath('glion-caux-terrain.png')})
 await clock.fill('43620'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'covered'); await expect(scene).toHaveCount(0)
 await expect(page.getByRole('button', {name: /Pause motion/})).toBeVisible(); await page.getByRole('button', {name: /Pause motion/}).click()
 await clock.fill('43700'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await card.getByRole('button', {name: 'Return to map', exact: true}).click(); await expect(scene).toHaveCount(0); await expect(clock).toHaveValue('43700')
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click(); await expect(scene).toHaveAttribute('data-rendered', 'true'); expect(requests).toBe(1)
 await clock.fill('44200'); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel'); await expect(scene).toHaveCount(0)
 await clock.fill('44510'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(scene).toHaveCount(0)
 await card.getByRole('button', {name: /Replay journey/}).click(); await expect(clock).toHaveValue('41640'); await expect(status).toContainText('Rail and ground heights differ')
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.getByRole('combobox', {name: 'Direction', exact: true}).selectOption('descent')
 await expect(clock).toHaveValue('44820'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await clock.fill('44860'); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel'); await expect(scene).toHaveCount(0)
 await clock.fill('46000'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await page.screenshot({path: info.outputPath('glion-downhill-terrain.png')})
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.locator('nav button').filter({has: page.getByText('Glion', {exact: true})}).click()
 await expect(clock).toHaveValue('47400'); await expect(status).toHaveAttribute('data-terrain-status', 'interchange'); await expect(scene).toHaveCount(0)
 await expect(card).toContainText('Until departure 9:00')
 await clock.fill('47940'); await expect(funicularScene).toHaveAttribute('data-rendered', 'true'); await expect(scene).toHaveCount(0); await expect(card).toContainText('swissALTI3D 2021')
 await page.screenshot({path: info.outputPath('glion-downhill-funicular-terrain.png')})
 await clock.fill('48060'); await expect(status).toContainText('Passing loop'); await expect(funicularScene).toHaveCount(0)
 await clock.fill('48290'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(page.getByRole('button', {name: /Resume motion/})).toBeVisible()
 await card.getByRole('button', {name: 'Exit journey', exact: true}).click(); await expect(scene).toHaveCount(0)
 expect(requests).toBe(1); expect(funicularRequests).toBe(1); expect(errors).toEqual([])
 if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('combined terrain retries failures and refuses unlisted downhill geometry without moving the clock', async ({page}) => {
 let mode = 'failed'
 await page.route('**/rochers-ascent-terrain.json', async route => {
  if (mode === 'failed') return route.fulfill({status: 503, body: 'unavailable'})
  const response = await route.fetch(), data = await response.json()
  if (mode === 'unlisted') delete data.routes[0].reverseTripIds
  await route.fulfill({response, json: data})
 })
 await page.goto('/?study=territet&date=2026-09-04&time=46000&glion=.ojp-91-37-F.1.TA.89.j26')
 const card = page.locator('.glion-journey'), clock = page.locator('.scrubber input'), status = card.locator('[data-terrain-status]'), scene = page.locator('.rochers-terrain-scene')
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(clock).toHaveValue('46000')
 await clock.fill('48000'); await expect(page.locator('.territet-terrain-scene')).toHaveAttribute('data-rendered', 'true'); await expect(status).toHaveAttribute('data-terrain-status', 'outdoor')
 await clock.fill('46000'); await expect(page.locator('.territet-terrain-scene')).toHaveCount(0); await expect(status).toHaveAttribute('data-terrain-status', 'error')
 mode = 'unlisted'; await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(scene).toHaveCount(0); await expect(clock).toHaveValue('46000')
 mode = 'valid'; await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect(scene).toHaveAttribute('data-rendered', 'true'); await expect(clock).toHaveValue('46000')
 await page.locator('.train-search input').fill('Caux')
 await page.getByRole('option').filter({has: page.locator('.result-service', {hasText: /^Caux$/})}).click()
 await expect(card).toHaveCount(0); await expect(scene).toHaveCount(0); await expect(page.locator('.station-card .service')).toHaveText('Caux')
})

test('a funicular terrain failure leaves railway terrain and the Glion interchange usable', async ({page}) => {
 let mode = 'failed', railwayRequests = 0, funicularRequests = 0
 page.on('request', r => {if (r.url().includes('rochers-ascent-terrain.json')) railwayRequests++})
 await page.route('**/territet-ascent-terrain.json', async route => {
  funicularRequests++
  if (mode === 'failed') return route.fulfill({status: 503, body: 'unavailable'})
  const response = await route.fetch(), data = await response.json()
  if (mode === 'unreviewed') data.contextTracks.pop()
  await route.fulfill({response, json: data})
 })
 await page.goto('/?study=territet&date=2026-09-04&time=41700&glion=.ojp-91-37-F.1.TA.45.j26')
 const card = page.locator('.glion-journey'), clock = page.locator('.scrubber input'), status = card.locator('[data-terrain-status]')
 await expect(clock).toHaveValue('41700')
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(clock).toHaveValue('41700')
 await clock.fill('42960'); await expect(page.locator('.rochers-terrain-scene')).toHaveAttribute('data-rendered', 'true')
 await expect(status).toHaveAttribute('data-terrain-status', 'outdoor')
 await clock.fill('42000'); await expect(status).toHaveAttribute('data-terrain-status', 'interchange')
 await expect(page.locator('.rochers-terrain-scene, .territet-terrain-scene')).toHaveCount(0)
 await expect(card.getByRole('button', {name: 'Retry terrain', exact: true})).toHaveCount(0)
 await expect(card).toContainText('Until departure 4:00')
 await clock.fill('41700'); mode = 'unreviewed'
 await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect.poll(() => funicularRequests).toBe(2)
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(clock).toHaveValue('41700')
 mode = 'valid'; await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect(page.locator('.territet-terrain-scene')).toHaveAttribute('data-rendered', 'true')
 await expect(clock).toHaveValue('41700'); expect(funicularRequests).toBe(3); expect(railwayRequests).toBe(1)
 await card.getByRole('button', {name: 'Return to map', exact: true}).click()
 await expect(page.locator('.territet-terrain-scene')).toHaveCount(0)
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(page.locator('.territet-terrain-scene')).toHaveAttribute('data-rendered', 'true')
 expect(funicularRequests).toBe(3); expect(railwayRequests).toBe(1)
 await card.getByRole('button', {name: 'Exit journey', exact: true}).click()
 await expect(page.locator('.rochers-terrain-scene, .territet-terrain-scene')).toHaveCount(0)
})
