import {expect,test} from '@playwright/test'
test('Gornergrat terrain preserves calls, tunnels, gallery, arrival and map return',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 let requests=0;page.on('request',r=>{if(r.url().includes('gornergrat-ascent-terrain.json'))requests++})
 await page.goto('/?study=gornergrat')
 await page.getByRole('button',{name:/Follow Zermatt to Gornergrat/}).click()
 const card=page.locator('.gornergrat-ascent'),clock=page.locator('.scrubber input'),scene=page.locator('.gornergrat-terrain-scene')
 await expect(card).toBeVisible();await expect(clock).toHaveValue('43200')
 expect(requests).toBe(0)
 await clock.fill('45000');await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(scene).toHaveAttribute('data-rendered','true');await expect(clock).toHaveValue('45000');expect(requests).toBe(1)
 await expect(page.locator('.map-navigation')).toBeHidden()
 await page.screenshot({path:info.outputPath('gornergrat-terrain-summit.png')})
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('button').filter({hasText:'Riffelalp'}).click()
 await expect(clock).toHaveValue('44100');await expect(scene).toHaveAttribute('data-stopped','true')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await clock.fill('43620');await expect(scene).toHaveCount(0)
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','tunnel')
 await clock.fill('44460');await expect(scene).toHaveCount(0)
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','covered')
 await page.screenshot({path:info.outputPath('gornergrat-terrain-gallery.png')})
 // Cross the first conservative tunnel boundary on the existing playing clock.
 await clock.fill('43570');await expect(scene).toHaveCount(1)
 await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','tunnel')
 await expect(page.getByRole('button',{name:/Pause motion/})).toBeVisible()
 await page.getByRole('button',{name:/Pause motion/}).click()
 // Gallery exit automatically returns to terrain and continues advancing.
 await clock.fill('44540');await expect(scene).toHaveCount(0)
 await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(scene).toHaveCount(1)
 await expect(page.getByRole('button',{name:/Pause motion/})).toBeVisible()
 await page.getByRole('button',{name:/Pause motion/}).click()
 await clock.fill('45000');await card.getByRole('button',{name:'Return to map',exact:true}).click()
 await expect(scene).toHaveCount(0);await expect(clock).toHaveValue('45000')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click();await expect(scene).toHaveCount(1);expect(requests).toBe(1)
 await clock.fill('45170');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay ascent/}).click();await expect(clock).toHaveValue('43200');await expect(scene).toHaveCount(1)
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 // The dated 08:24 departure calls at Ferienhaus; the default noon train does not.
 await card.getByRole('combobox',{name:'Choose a departure'}).selectOption('.ojp-93-48.1.TA.39.j26')
 await expect(clock).toHaveValue('30240')
 await expect(card.locator('nav button')).toHaveCount(7)
 await card.getByRole('button').filter({hasText:'Ferienhaus'}).click();await expect(scene).toHaveAttribute('data-stopped','true')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await page.screenshot({path:info.outputPath('gornergrat-terrain-zermatt.png')})
 await card.getByRole('button',{name:'Exit ascent',exact:true}).click();await expect(scene).toHaveCount(0)
 if(isMobile)expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
for(const failure of ['request','malformed'])test(`Gornergrat ${failure} terrain failure retains the clock and has retry`,async({page})=>{
 let fail=true
 await page.route('**/gornergrat-ascent-terrain.json',r=>fail?r.fulfill({status:failure==='request'?503:200,contentType:'application/json',body:failure==='request'?'unavailable':'null'}):r.continue())
 await page.goto('/?study=gornergrat');await page.getByRole('button',{name:/Follow Zermatt to Gornergrat/}).click()
 const card=page.locator('.gornergrat-ascent')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error');await expect(page.locator('.scrubber input')).toHaveValue('43200')
 fail=false;await card.getByRole('button',{name:'Retry terrain',exact:true}).click()
 await expect(page.locator('.gornergrat-terrain-scene')).toHaveAttribute('data-rendered','true')
})
