import {expect,test} from '@playwright/test'
test('Gornergrat descent follows its dated calls through terrain, gallery, arrival and direction changes',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('gornergrat-ascent-terrain.json'))requests++})
 await page.goto('/?study=gornergrat');await page.getByRole('button',{name:/Follow Zermatt to Gornergrat/}).click()
 const card=page.locator('.gornergrat-ascent'),clock=page.locator('.scrubber input'),scene=page.locator('.gornergrat-terrain-scene')
 await expect(card).toBeVisible();await expect(clock).toHaveValue('43200')
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(card).toHaveAttribute('data-direction','descent');await expect(clock).toHaveValue('42900')
 await expect(card.getByRole('heading')).toHaveText('Gornergrat → Zermatt')
 await expect(card.getByRole('combobox',{name:'Choose a departure'}).locator('option')).toHaveCount(26)
 await expect(card.locator('nav button strong')).toHaveText(['Gornergrat','Rotenboden','Riffelberg','Riffelalp','Findelbach','Zermatt GGB'])
 expect(requests).toBe(0)
 await clock.fill('43020');await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(scene).toHaveAttribute('data-rendered','true');await expect(clock).toHaveValue('43020');expect(requests).toBe(1)
 await page.screenshot({path:info.outputPath('gornergrat-descent-terrain.png')})
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('button').filter({hasText:'Riffelberg'}).click()
 await expect(clock).toHaveValue('43800');await expect(scene).toHaveAttribute('data-stopped','true')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await clock.fill('43830');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','covered')
 await expect(page.getByRole('button',{name:/Pause motion/})).toBeVisible();await page.getByRole('button',{name:/Pause motion/}).click()
 await clock.fill('44040');await page.getByRole('button',{name:/Resume motion/}).click();await expect(scene).toHaveCount(1)
 await page.getByRole('button',{name:/Pause motion/}).click()
 await clock.fill('44660');await expect(scene).toHaveCount(0);await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','tunnel')
 await clock.fill('45530');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived at Zermatt GGB')
 await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay descent/}).click();await expect(clock).toHaveValue('42900')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('combobox',{name:'Choose a departure'}).selectOption({index:0});await expect(clock).toHaveValue('27300')
 await expect(card.locator('nav button')).toHaveCount(7)
 await card.getByRole('button').filter({hasText:'Ferienhaus'}).click();await expect(scene).toHaveAttribute('data-stopped','true')
 await expect(scene).toHaveAttribute('data-rendered','true')
 await page.screenshot({path:info.outputPath('gornergrat-descent-stops.png')})
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('ascent')
 await expect(clock).toHaveValue('43200');await expect(card).toHaveAttribute('data-direction','ascent');await expect(scene).toHaveCount(1)
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(clock).toHaveValue('42900');expect(requests).toBe(1)
 await card.getByRole('button',{name:'Exit descent',exact:true}).click();await expect(scene).toHaveCount(0)
 if(isMobile)expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
test('an older ascent-only artifact leaves descents on the map with retry',async({page})=>{
 let old=true
 await page.route('**/gornergrat-ascent-terrain.json',async r=>{
  if(!old)return r.continue()
  const response=await r.fetch(),value=await response.json()
  delete value.routes[0].reverseTripIds
  return r.fulfill({response,json:value})
 })
 await page.goto('/?study=gornergrat');await page.getByRole('button',{name:/Follow Zermatt to Gornergrat/}).click()
 const card=page.locator('.gornergrat-ascent')
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(page.locator('.scrubber input')).toHaveValue('42900')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error')
 await expect(card).toContainText('The descent remains on the map.');await expect(page.locator('.gornergrat-terrain-scene')).toHaveCount(0)
 old=false;await card.getByRole('button',{name:'Retry terrain',exact:true}).click()
 await expect(page.locator('.gornergrat-terrain-scene')).toHaveAttribute('data-rendered','true')
 await expect(page.locator('.scrubber input')).toHaveValue('42900')
})
