import {expect,test} from '@playwright/test'
test('Gornergrat loads on demand and follows dated calls through arrival and replay',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('gornergrat-day.json'))requests++})
 await page.goto('/');await expect(page.getByRole('button',{name:/Pause motion|Resume motion/})).toBeVisible();expect(requests).toBe(0)
 await page.getByRole('button',{name:'Explore studies',exact:true}).click()
 await page.getByRole('dialog').getByRole('button').filter({hasText:'Zermatt → Gornergrat'}).click()
 await expect(page.getByRole('heading',{name:'Zermatt → Gornergrat',exact:true})).toBeVisible()
 await page.waitForTimeout(1200) // Allow the map camera to settle before the overview screenshot.
 await page.screenshot({path:info.outputPath('gornergrat-map.png')})
 await page.getByRole('button',{name:/Follow Zermatt to Gornergrat/}).click()
 const card=page.locator('.gornergrat-ascent'),clock=page.locator('.scrubber input')
 await expect(card).toHaveAttribute('data-phase','rail');expect(requests).toBe(1)
 await expect(card.locator('option')).toHaveCount(26)
 await expect(clock).toHaveValue('43200');await expect(card).toContainText('12:00 → 12:33')
 await card.getByRole('button').filter({hasText:'Riffelalp'}).click()
 await expect(card.locator('[aria-current="step"]')).toContainText('Riffelalp')
 await page.waitForTimeout(1200) // Review the settled camera after seeking to the station.
 await page.screenshot({path:info.outputPath('gornergrat-ascent.png')})
 await clock.fill('45170');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete')
 await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay ascent/}).click();await expect(clock).toHaveValue('43200')
 await card.getByRole('combobox',{name:'Choose a departure'}).selectOption({index:0});await expect(clock).toHaveValue('25200')
 await clock.fill('0');await expect(card).toHaveAttribute('data-phase','before')
 await card.getByRole('button',{name:'Exit ascent',exact:true}).click()
 await page.locator('.train-search input').fill('Riffelalp')
 await expect(page.getByRole('option').first()).toBeVisible()
 if(isMobile){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.mobile-study-picker .mobile-picker__trigger')).toContainText('GGR')}
 expect(errors).toEqual([])
})
test('Gornergrat request retry and dated station links preserve the study',async({page})=>{
 let fail=true;await page.route('**/gornergrat-day.json',r=>fail?r.fulfill({status:503,body:'unavailable'}):r.continue())
 await page.goto('/?study=gornergrat&date=2026-09-04&time=43200&station=Rotenboden')
 await expect(page.getByText('Gornergrat is unavailable. Retry or choose another study.')).toBeVisible()
 fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click()
 await expect(page.locator('.station-card .service')).toHaveText('Rotenboden')
 await expect(page.locator('.scrubber input')).toHaveValue('43200')
 await page.goto('/?study=gornergrat&date=2026-09-05&time=43200')
 await expect(page.getByText('The linked date is unavailable; showing the available timetable.')).toBeVisible()
})
