import { expect, test } from '@playwright/test'

test('Horgen evening is discoverable, plays, shares and preserves the afternoon recording', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Road recordings', exact: true }).click()
  const choice = page.getByRole('dialog').locator('a[href*="recording=horgen-evening-2026-09-08"]')
  await expect(choice).toContainText('61 recorded minutes')
  await expect(choice).toContainText('21:10–22:10')
  await choice.click()
  const card = page.locator('.cantonal-pilot')
  const clock = page.locator('.scrubber input')
  await expect(card).toContainText('Horgen · Seestrasse · 21:10–22:10')
  await expect(card).toContainText('61 complete recorded minutes · no gaps')
  await expect(card).toContainText('Mapped junction areas: 3')
  await expect(clock).toHaveAttribute('min', '76200')
  await expect(clock).toHaveAttribute('max', '79800')
  await expect(clock).toHaveValue('76200')
  await expect(page.locator('.road-corridor-card .metric-grid strong').nth(1)).toHaveText(/≈[1-9]/)
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await clock.inputValue())).toBeGreaterThan(76200)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await clock.fill('79800')
  await page.getByRole('button', { name: 'Share study', exact: true }).click()
  const url = await page.locator('.explore-link').inputValue()
  expect(url).toContain('recording=horgen-evening-2026-09-08')
  await page.goto(url)
  await expect(clock).toHaveValue('79800')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await page.screenshot({ path: info.outputPath('horgen-evening.png') })
  const picker = page.getByRole('combobox', { name: 'Road recordings', exact: true })
  await expect(picker.locator('option[value="horgen-evening-2026-09-08"]')).toContainText('2026-09-08 · 21:10–22:10')
  await picker.selectOption('horgen-2026-09-08')
  await expect(clock).toHaveValue('49440')
  await expect(card).toContainText('Missing observations')
  expect(errors).toEqual([])
})

test('a failed evening download retries the evening identity with accurate recording copy', async ({ page }) => {
  await page.route('**/horgen-evening-road-pilot.json', route => route.fulfill({ status: 503, body: '' }))
  await page.goto('/?recording=horgen-evening-2026-09-08&time=79800')
  await expect(page.locator('.cantonal-pilot')).toContainText('Try again')
  await page.unroute('**/horgen-evening-road-pilot.json')
  await page.getByRole('button', { name: 'Play Horgen recording', exact: true }).click()
  await expect(page.locator('.cantonal-pilot')).toContainText('61 complete recorded minutes')
  await expect(page.locator('.scrubber input')).toHaveValue('79800')
})
