import { expect, test } from '@playwright/test'
test('measured Jungfrau terrain preserves the clock through dwells, tunnels and map return', async ({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 let requests=0;page.on('request',r=>{if(r.url().includes('jungfrau-ascent-terrain.json'))requests++})
 await page.goto('/?study=jungfrau')
 await page.getByRole('button',{name:/Follow the ascent via Wengen/}).click()
 const card=page.locator('.jungfrau-ascent'),clock=page.locator('.scrubber input'),scene=page.locator('.jungfrau-terrain-scene')
 await expect(card).toBeVisible();expect(requests).toBe(0)
 await clock.fill('48060')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(scene.locator('canvas')).toBeVisible();await expect(scene).toHaveAttribute('data-leg','1')
 await expect(clock).toHaveValue('48060');expect(requests).toBe(1)
 await expect(scene).toHaveAttribute('data-rendered','true')
 await expect(page.locator('.map-navigation')).toBeHidden()
 await page.screenshot({path:info.outputPath('jungfrau-terrain-wengen.png')})
 // Wengen's published dwell is held on its source rail position.
 await clock.fill('47580');await expect(scene).toHaveAttribute('data-stopped','true')
 const progress=await scene.getAttribute('data-progress')
 await clock.fill('47640');await expect(scene).toHaveAttribute('data-progress',progress!)
 // Main summit tunnel stays on the mapped alignment with the terrain preference retained.
 await clock.fill('52000');await expect(scene).toHaveCount(0)
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','tunnel')
 await expect(card.getByRole('button',{name:'Return to map',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.screenshot({path:info.outputPath('jungfrau-terrain-tunnel.png')})
 // Cross the first tunnel portal without pausing or jumping to another leg.
 await clock.fill('46930');await expect(scene).toHaveCount(1)
 await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','tunnel')
 await expect(page.getByRole('button',{name:/Pause motion/})).toBeVisible()
 await page.getByRole('button',{name:/Pause motion/}).click()
 await clock.fill('48060');await expect(scene).toHaveCount(1)
 await card.getByRole('button',{name:'Return to map',exact:true}).click();await expect(scene).toHaveCount(0)
 await expect(clock).toHaveValue('48060')
 if(isMobile)expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
test('terrain request failure has an explicit retry without replacing the ascent',async({page})=>{
 let fail=true
 await page.route('**/jungfrau-ascent-terrain.json',route=>fail?route.fulfill({status:503,body:'unavailable'}):route.continue())
 await page.goto('/?study=jungfrau');await page.getByRole('button',{name:/Follow the ascent via Wengen/}).click()
 const card=page.locator('.jungfrau-ascent')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error')
 await expect(page.locator('.scrubber input')).toHaveValue('43440')
 fail=false;await card.getByRole('button',{name:'Retry terrain',exact:true}).click()
 await expect(page.locator('.jungfrau-terrain-scene canvas')).toBeVisible()
})
test('malformed terrain fails back to the map and can be retried',async({page})=>{
 let malformed=true
 await page.route('**/jungfrau-ascent-terrain.json',route=>malformed?route.fulfill({status:200,contentType:'application/json',body:'null'}):route.continue())
 await page.goto('/?study=jungfrau');await page.getByRole('button',{name:/Follow the ascent via Wengen/}).click()
 const card=page.locator('.jungfrau-ascent')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error')
 malformed=false;await card.getByRole('button',{name:'Retry terrain',exact:true}).click()
 await expect(page.locator('.jungfrau-terrain-scene')).toHaveAttribute('data-rendered','true')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('combobox',{name:'Choose a departure'}).selectOption({index:0})
 await expect(page.locator('.scrubber input')).toHaveValue('23640')
 await expect(page.locator('.jungfrau-terrain-scene')).toHaveCount(1)
})
