import { expect, test } from '@playwright/test'
test('Jungfrau guide explains three approaches and preserves the selected map time', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?study=jungfrau&date=2026-09-04&time=43200')
  await expect(page.getByRole('button', { name: /Resume motion/ })).toBeVisible()
  const clock = page.locator('.scrubber input'); await clock.fill('43200')
  const entry = page.getByRole('button', { name: /Three approaches to Jungfraujoch/ })
  await entry.click()
  const guide = page.getByRole('dialog', { name: 'Three approaches to Jungfraujoch' })
  await expect(guide.locator('[data-approach]')).toHaveCount(3)
  await expect(guide).toContainText('Via Grindelwald & Kleine Scheidegg')
  await expect(guide).toContainText('distinct mapped endpoints')
  await page.screenshot({ path: info.outputPath('jungfrau-guide.png') })
  await guide.getByRole('button', { name: 'Close guide', exact: true }).click()
  await expect(entry).toBeFocused()
  await entry.click()
  await guide.locator('[data-approach="wengen"]').getByRole('button', { name: 'Wengen ↗', exact: true }).click()
  await expect(guide).toHaveCount(0)
  await expect(page.locator('.station-card .service')).toHaveText('Wengen')
  await expect(clock).toHaveValue('43200')
  expect(errors).toEqual([])
})
test('Jungfrau ascent follows three trains and both waits, then replays or exits for manual selection', async ({ page, isMobile }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?study=jungfrau')
  await page.getByRole('button', { name: /Three approaches to Jungfraujoch/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: /Follow the ascent via Wengen/ }).click()
  const card = page.locator('.jungfrau-ascent'), clock = page.locator('.scrubber input')
  await expect(card).toHaveAttribute('data-phase','leg-0')
  await expect(clock).toHaveValue('43440')
  await expect(card).toContainText('12:04 → 12:26')
  await expect(card).toContainText('13:58 → 14:41')
  await card.locator('summary').click()
  await expect(card).toContainText('no internal GTFS transfer minimum')
  await expect(card).toContainText('plus 10 minutes')
  await card.locator('summary').click()
  await card.locator('[data-stage="wait-0"]').click()
  await expect(card).toHaveAttribute('data-phase','wait-0')
  await expect(clock).toHaveValue('44760')
  await expect(card.locator('[aria-current="step"]')).toContainText('34 min')
  await clock.fill('46790'); await page.getByRole('button', { name: /Resume motion/ }).click()
  await expect(card).toHaveAttribute('data-phase','leg-1')
  await page.getByRole('button', { name: /Pause motion/ }).click()
  await card.locator('[data-stage="wait-1"]').click()
  await expect(card).toHaveAttribute('data-phase','wait-1')
  await expect(card.locator('[aria-current="step"]')).toContainText('20 min')
  await page.screenshot({ path: info.outputPath('jungfrau-ascent-wait.png') })
  await clock.fill('50270'); await page.getByRole('button', { name: /Resume motion/ }).click()
  await expect(card).toHaveAttribute('data-phase','leg-2')
  await page.getByRole('button', { name: /Pause motion/ }).click()
  await clock.fill('52850'); await page.getByRole('button', { name: /Resume motion/ }).click()
  await expect(card).toHaveAttribute('data-phase','complete')
  await expect(page.getByRole('button', { name: /Resume motion/ })).toBeVisible()
  await card.getByRole('button', { name: /Replay ascent/ }).click()
  await expect(clock).toHaveValue('43440')
  await card.getByRole('combobox', { name: 'Choose a departure' }).selectOption({index:0})
  await expect(clock).toHaveValue('23640')
  await clock.fill('0'); await expect(card).toHaveAttribute('data-phase','before')
  await card.locator('[data-stage="leg-0"]').click()
  await page.screenshot({ path: info.outputPath('jungfrau-ascent.png') })
  if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.locator('.train-search input').fill('Eiger Express')
  await page.getByRole('option').filter({ has: page.locator('.result-service b') }).first().click()
  await expect(card).toHaveCount(0)
  await expect(page.locator('.selected-card')).toContainText('not tracked cabins')
  expect(errors).toEqual([])
})
