import { expect, test } from '@playwright/test'

test('Kilchberg–Thalwil plays, shares and switches to Horgen on the same road', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?recording=kilchberg-thalwil-2026-09-08')
  const card = page.locator('.cantonal-pilot')
  const timeline = page.locator('.scrubber input')
  await expect(card).toContainText('Kilchberg–Thalwil · Seestrasse')
  await expect(card).toContainText('142 complete recorded minutes · no gaps')
  await expect(card).toContainText('Mapped junction areas: 3')
  await expect(card).toContainText('8 September 2026')
  await expect(timeline).toHaveAttribute('min', '51240')
  await expect(timeline).toHaveAttribute('max', '59700')
  await expect(timeline).toHaveValue('51240')
  await expect(page.locator('.road-corridor-card .metric-grid strong').nth(1)).toHaveText(/≈[1-9]/)
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await timeline.inputValue())).toBeGreaterThan(51240)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await timeline.fill('59700')
  await page.getByRole('button', { name: 'Share study', exact: true }).click()
  const url = await page.locator('.explore-link').inputValue()
  expect(url).toContain('recording=kilchberg-thalwil-2026-09-08')
  await page.goto(url)
  await expect(card).toContainText('Kilchberg–Thalwil · Seestrasse')
  await expect(timeline).toHaveValue('59700')
  await page.getByRole('combobox', { name: 'Road recordings', exact: true }).selectOption('horgen-2026-09-08')
  await expect(card).toContainText('Horgen · Seestrasse')
  await expect(timeline).toHaveValue('49440')
  await page.getByRole('combobox', { name: 'Road recordings', exact: true }).selectOption('kilchberg-thalwil-2026-09-08')
  await expect(card).toContainText('142 complete recorded minutes')
  await expect(timeline).toHaveValue('51240')
  expect(errors).toEqual([])
})

test('the third recording is discoverable and retry retains its identity', async ({ page }) => {
  await page.route('**/kilchberg-thalwil-road-pilot.json', route => route.fulfill({ status: 503, body: '' }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Road recordings', exact: true }).click()
  const choice = page.getByRole('dialog').getByRole('link', { name: /Kilchberg–Thalwil/ })
  await expect(choice).toContainText('142 recorded minutes')
  await choice.click()
  await expect(page.locator('.cantonal-pilot')).toContainText('Try again')
  await page.unroute('**/kilchberg-thalwil-road-pilot.json')
  await page.getByRole('button', { name: 'Play Kilchberg–Thalwil recording' }).click()
  await expect(page.locator('.cantonal-pilot')).toContainText('142 complete recorded minutes')
})
