import { expect, test } from '@playwright/test'

test('Meilen opens from the picker, shares its final minute and switches ZH 17 recordings', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Road recordings', exact: true }).click()
  const choice = page.getByRole('dialog').locator('a[href*="recording=meilen-seestrasse-"]')
  await expect(choice).toContainText('142 recorded minutes')
  await choice.click()
  const card = page.locator('.cantonal-pilot')
  const clock = page.locator('.scrubber input')
  await expect(card).toContainText('Meilen · Seestrasse')
  await expect(card).toContainText('142 complete recorded minutes · no gaps')
  await expect(card).toContainText('Mapped junction areas: 3')
  await expect(clock).toHaveValue('51240')
  await expect(clock).toHaveAttribute('max', '59700')
  await expect(page.locator('.road-corridor-card .metric-grid strong').nth(1)).toHaveText(/≈[1-9]/)
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await clock.inputValue())).toBeGreaterThan(51240)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await page.screenshot({ path: info.outputPath('meilen-seestrasse.png') })
  await clock.fill('59700')
  await page.getByRole('button', { name: 'Share study', exact: true }).click()
  const url = await page.locator('.explore-link').inputValue()
  expect(url).toContain('recording=meilen-seestrasse-2026-09-08')
  await page.goto(url)
  await expect(card).toContainText('Meilen · Seestrasse')
  await expect(clock).toHaveValue('59700')
  const recordings = page.getByRole('combobox', { name: 'Road recordings', exact: true })
  await recordings.selectOption('meilen-staefa-2026-09-08')
  await expect(card).toContainText('245 complete recorded minutes')
  await expect(clock).toHaveValue('48180')
  await recordings.selectOption('meilen-seestrasse-2026-09-08')
  await expect(card).toContainText('Meilen · Seestrasse')
  await expect(clock).toHaveValue('51240')
  expect(errors).toEqual([])
})
