import { expect, test } from '@playwright/test'

test('Meilen–Stäfa opens from the catalog, plays and shares its final observation', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Road recordings', exact: true }).click()
  const choice = page.getByRole('dialog').getByRole('link', { name: /Meilen–Stäfa/ })
  await expect(choice).toContainText('245 recorded minutes')
  await choice.click()
  const pilot = page.locator('.cantonal-pilot')
  const clock = page.locator('.scrubber input')
  await expect(pilot).toContainText('Meilen–Stäfa · Seestrasse')
  await expect(pilot).toContainText('245 complete recorded minutes · no gaps')
  await expect(pilot).toContainText('Mapped junction areas: 2')
  await expect(clock).toHaveAttribute('min', '48180')
  await expect(clock).toHaveAttribute('max', '62820')
  await expect(clock).toHaveValue('48180')
  await expect(page.locator('.road-corridor-card .metric-grid strong').nth(1)).toHaveText(/≈[1-9]/)
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await clock.inputValue())).toBeGreaterThan(48180)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await page.screenshot({ path: info.outputPath('meilen-pilot.png') })
  await clock.fill('62820')
  await page.getByRole('button', { name: 'Share study', exact: true }).click()
  const url = await page.locator('.explore-link').inputValue()
  expect(url).toContain('recording=meilen-staefa-2026-09-08')
  await page.goto(url)
  await expect(pilot).toContainText('Meilen–Stäfa · Seestrasse')
  await expect(clock).toHaveValue('62820')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await pilot.getByRole('button', { name: 'Return to morning roads' }).click()
  await expect(clock).toHaveAttribute('min','24300')
  expect(errors).toEqual([])
})
