import {expect,test} from '@playwright/test'
test('Pilatus loads on request and follows dated trains in both directions',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('pilatus-day.json'))requests++})
 await page.goto('/');await expect(page.getByRole('button',{name:'Explore studies',exact:true})).toBeVisible();expect(requests).toBe(0)
 await page.getByRole('button',{name:'Explore studies',exact:true}).click()
 await page.getByRole('dialog').getByRole('button').filter({hasText:'Alpnachstad → Pilatus Kulm'}).click()
 await expect(page.getByRole('heading',{name:'Alpnachstad → Pilatus Kulm',exact:true})).toBeVisible()
 await page.waitForTimeout(1200)
 await page.screenshot({path:info.outputPath('pilatus-map.png')})
 await page.getByRole('button',{name:/Follow the Pilatus railway/}).click()
 const card=page.locator('.pilatus-journey'),clock=page.locator('.scrubber input')
 await expect(card).toHaveAttribute('data-phase','rail');await expect(clock).toHaveValue('44100');expect(requests).toBe(1)
 await expect(card.getByRole('combobox',{name:'Choose a departure'}).locator('option')).toHaveCount(17)
 await card.getByRole('button').filter({hasText:'Ämsigen'}).click();await expect(clock).toHaveValue('44700')
 await expect(card).toContainText('Boarding depends on available space')
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('pilatus-journey.png')})
 await clock.fill('45710');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Pilatus Kulm')
 await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay journey/}).click();await expect(clock).toHaveValue('44100')
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(clock).toHaveValue('44040');await expect(card.getByRole('heading')).toHaveText('Pilatus Kulm → Alpnachstad')
 await expect(card.locator('nav button strong')).toHaveText(['Pilatus Kulm','Ämsigen · request stop','Alpnachstad PB'])
 await clock.fill('46010');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Alpnachstad PB')
 await card.getByRole('combobox',{name:'Choose a departure'}).selectOption({index:0});await expect(clock).toHaveValue('31440')
 await card.getByRole('button',{name:'Exit journey',exact:true}).click()
 await page.locator('.train-search input').fill('Aemsigen');await expect(page.getByRole('option').first()).toBeVisible()
 if(isMobile){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.mobile-study-picker .mobile-picker__trigger')).toContainText('PIL')}
 expect(errors).toEqual([])
})
test('Pilatus retry and dated station links keep the correct study',async({page})=>{
 let fail=true;await page.route('**/pilatus-day.json',r=>fail?r.fulfill({status:503,body:'unavailable'}):r.continue())
 await page.goto('/?study=pilatus&date=2026-09-04&time=44700&station=Aemsigen')
 await expect(page.getByText('Pilatus is unavailable. Retry or choose another study.')).toBeVisible()
 fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click()
 await expect(page.locator('.station-card .service')).toHaveText('Aemsigen');await expect(page.locator('.scrubber input')).toHaveValue('44700')
 await page.goto('/?study=pilatus&date=2026-09-05&time=43200')
 await expect(page.getByText('The linked date is unavailable; showing the available timetable.')).toBeVisible()
})
