import {expect,test} from '@playwright/test'
test('Pilatus terrain preserves source calls and the clock through both directions and covered sections',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('pilatus-ascent-terrain.json'))requests++})
 await page.goto('/?study=pilatus');await page.getByRole('button',{name:/Follow the Pilatus railway/}).click()
 const card=page.locator('.pilatus-journey'),clock=page.locator('.scrubber input'),scene=page.locator('.pilatus-terrain-scene'),status=card.locator('[data-terrain-status]')
 await expect(clock).toHaveValue('44100');expect(requests).toBe(0)
 await clock.fill('44620');await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(scene).toHaveAttribute('data-rendered','true');await expect(clock).toHaveValue('44620');expect(requests).toBe(1)
 await page.screenshot({path:info.outputPath('pilatus-ascent-terrain.png')})
 await clock.fill('44430');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(status).toHaveAttribute('data-terrain-status','tunnel');await expect(scene).toHaveCount(0)
 await expect(page.getByRole('button',{name:/Pause motion/})).toBeVisible();await page.getByRole('button',{name:/Pause motion/}).click()
 await clock.fill('44470');await expect(scene).toHaveAttribute('data-rendered','true')
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('button').filter({hasText:'Ämsigen'}).click();await expect(clock).toHaveValue('44700');await expect(scene).toHaveAttribute('data-stopped','true')
 await expect(card).toContainText('Boarding depends on available space')
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(clock).toHaveValue('44040');await expect(status).toHaveAttribute('data-terrain-status','covered');await expect(scene).toHaveCount(0)
 await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await clock.fill('44400');await expect(scene).toHaveAttribute('data-rendered','true');expect(requests).toBe(1)
 await page.screenshot({path:info.outputPath('pilatus-descent-terrain.png')})
 await clock.fill('44130');await expect(status).toHaveAttribute('data-terrain-status','tunnel');await expect(scene).toHaveCount(0)
 await clock.fill('45250');await expect(status).toHaveAttribute('data-terrain-status','tunnel')
 await clock.fill('45500');await expect(scene).toHaveAttribute('data-rendered','true')
 await card.getByRole('button',{name:'Return to map',exact:true}).click();await expect(scene).toHaveCount(0);await expect(clock).toHaveValue('45500')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click();await expect(scene).toHaveAttribute('data-rendered','true');expect(requests).toBe(1)
 await clock.fill('46010');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Alpnachstad PB');await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay journey/}).click();await expect(clock).toHaveValue('44040');await expect(status).toHaveAttribute('data-terrain-status','covered')
 await card.getByRole('button',{name:'Exit journey',exact:true}).click();await expect(scene).toHaveCount(0)
 if(isMobile)expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
test('Pilatus terrain request failure and unaudited descent data stay on the map with retry',async({page})=>{
 let mode='failure'
 await page.route('**/pilatus-ascent-terrain.json',async r=>{
  if(mode==='failure')return r.fulfill({status:503,body:'unavailable'})
  if(mode==='valid')return r.continue()
  const response=await r.fetch(),value=await response.json();delete value.routes[0].reverseTripIds
  return r.fulfill({response,json:value})
 })
 await page.goto('/?study=pilatus');await page.getByRole('button',{name:/Follow the Pilatus railway/}).click()
 const card=page.locator('.pilatus-journey'),clock=page.locator('.scrubber input'),scene=page.locator('.pilatus-terrain-scene')
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent');await clock.fill('44400')
 await card.getByRole('button',{name:'Follow in measured terrain',exact:true}).click()
 await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error');await expect(card).toContainText('The journey remains on the map.');await expect(scene).toHaveCount(0)
 mode='unaudited';await card.getByRole('button',{name:'Retry terrain',exact:true}).click();await expect(card.locator('[data-terrain-status]')).toHaveAttribute('data-terrain-status','error');await expect(scene).toHaveCount(0)
 mode='valid';await card.getByRole('button',{name:'Retry terrain',exact:true}).click();await expect(scene).toHaveAttribute('data-rendered','true');await expect(clock).toHaveValue('44400')
})
