import { expect, test, type Page } from '@playwright/test'

async function openSequence(page: Page, mobile: boolean) {
  await page.goto('/')
  if (mobile) {
    await page.locator('.mobile-study-picker .mobile-picker__trigger').click()
    await page.getByRole('option', { name: /RIGI/ }).click()
  } else await page.getByRole('button', { name: 'Explore Lake Lucerne and Rigi', exact: true }).click()
  await page.getByRole('button', { name: 'Follow lake to summit', exact: false }).click()
  await expect(page.locator('.rigi-sequence')).toHaveAttribute('data-phase', 'boat')
}

test('lake-to-summit shares the map clock through both handoffs, replay and a different departure', async ({ page, isMobile }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openSequence(page, isMobile)
  const card = page.locator('.rigi-sequence'), clock = page.locator('.scrubber input[type="range"]')
  await expect(clock).toHaveValue('43920')
  await expect(card).toContainText('12:12 → 13:09')
  await expect(card).toContainText('13:15 → 13:47')
  await expect(card).toContainText('50 m walk · timetable minimum 1 min')
  await expect(card).toContainText('Connection not guaranteed')
  await card.getByRole('button', { name: /Change at Vitznau/ }).click()
  await expect(clock).toHaveValue('47340')
  await expect(card).toHaveAttribute('data-phase', 'interchange')
  await page.screenshot({ path: info.outputPath('rigi-sequence-interchange.png') })
  await clock.fill('47690')
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect(card).toHaveAttribute('data-phase', 'rail')
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await clock.fill('49620')
  await expect(card).toHaveAttribute('data-phase', 'complete')
  await card.getByRole('button', { name: /Replay/ }).click()
  await expect(card).toHaveAttribute('data-phase', 'boat')
  await clock.fill('47330')
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect(card).toHaveAttribute('data-phase', 'interchange')
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await card.getByRole('combobox').selectOption({ index: 0 })
  await expect(clock).toHaveValue('29520')
  await expect(card).toContainText('08:12 → 09:09')
  await clock.fill('0')
  await expect(card).toHaveAttribute('data-phase', 'before')
  await card.getByRole('button', { name: /Boat 5/ }).click()
  await page.screenshot({ path: info.outputPath('rigi-sequence-boat.png') })
  await card.getByRole('button', { name: 'Leave sequence', exact: true }).click()
  await expect(card).toHaveCount(0)
  await expect(page.locator('.network-card')).toContainText('190')
  expect(errors).toEqual([])
})

test('manual service selection exits sequence and terrain remains independently playable', async ({ page, isMobile }) => {
  await openSequence(page, isMobile)
  await page.locator('.train-search input').fill('Weggis-Rigi Kaltbad')
  await page.getByRole('option').filter({ has: page.locator('.result-service b') }).first().click()
  await expect(page.locator('.rigi-sequence')).toHaveCount(0)
  await expect(page.locator('.selected-card')).toContainText('Mapped cableway alignment')
  await page.locator('.train-search input').fill('')
  await page.getByRole('button', { name: 'Follow lake to summit', exact: false }).click()
  await page.locator('.sequence-evidence summary').click()
  await page.getByRole('button', { name: 'Explore Vitznau terrain', exact: false }).click()
  await expect(page.locator('.experience')).toHaveClass(/view-journey/)
  await expect(page.locator('.rigi-sequence')).toHaveCount(0)
})
