import { expect, test } from '@playwright/test'

test('Rigi day rhythm exposes quiet gaps, departures, both approaches and the study boundary', async ({ page, isMobile }, info) => {
  const errors: string[] = [], optional: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.url().includes('RigiDayRhythm') || r.url().includes('-corridor.json')) optional.push(r.url()) })
  await page.goto('/?study=rigi-lake&time=0')
  const open = page.getByRole('button', { name: 'A day on lake and mountain →', exact: true })
  await expect(open).toBeVisible()
  expect(optional).toHaveLength(0)
  // Opening preserves playback state; pause first so boundaries are deterministic.
  const pause = page.getByRole('button', { name: /Pause motion/i })
  if (await pause.isVisible()) await pause.click()
  await page.locator('.scrubber input').fill('0')
  await open.click()
  const card = page.locator('.rigi-day-rhythm'), scrubber = page.locator('.scrubber input')
  await expect(card).toContainText('2026-09-04')
  await expect(card.getByText('Quiet now', { exact: true })).toHaveCount(4)
  await expect(scrubber).toHaveValue('0')
  await expect(card.locator('[data-mode="vitznau"]')).toContainText('06:35')
  await expect(card.locator('[data-mode="vitznau"]')).toContainText('Rigi Staffelhöhe')
  await card.locator('[data-mode="cable"] button').click()
  await expect(scrubber).toHaveValue('24000')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await expect(card.locator('[data-mode="cable"]')).toContainText('1 underway')
  await scrubber.fill('24700')
  await expect(card.locator('[data-mode="cable"]')).toContainText('Quiet now')
  await card.getByRole('button', { name: 'Close day rhythm' }).scrollIntoViewIfNeeded()
  await card.evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({ path: info.outputPath('rigi-day-rhythm.png') })
  await scrubber.fill('86390')
  await expect(card.locator('[data-mode="boats"]')).toContainText('1 underway')
  await expect(card.locator('[data-mode="cable"]')).toContainText('No later departure in this study')
  await scrubber.fill('86400')
  await expect(card.getByText('End of study window', { exact: true })).toHaveCount(4)
  await card.getByRole('button', { name: /Return to first departure/ }).click()
  await expect(scrubber).toHaveValue('22800')
  await expect(card.locator('[data-mode="boats"]')).toContainText('1 underway')
  await card.locator('summary').click()
  await expect(card).toContainText('Other dates and seasonal closures are not covered')
  await expect(card.locator('a')).toHaveAttribute('href', './methodology.html#rigi-rhythm')
  if (isMobile) {
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const box = (await card.boundingBox())!, transport = (await page.locator('.transport').boundingBox())!
    expect(box.y + box.height).toBeLessThan(transport.y)
  }
  await card.getByRole('button', { name: 'Close day rhythm' }).click()
  await expect(open).toBeVisible()
  await expect(scrubber).toHaveValue('22800')
  expect(optional.every(url => !url.includes('-corridor.json'))).toBe(true)
  expect(errors).toEqual([])
})
