import { expect, test } from '@playwright/test'

test('both sequence approaches enter measured terrain at the same clock time, hold dwells and return to the map', async ({ page, isMobile }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', r => { if (r.url().includes('vitznau-rigi-corridor.json')) requests.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/?study=rigi-lake&time=43200')
  await page.getByRole('button', { name: /Follow lake to summit/ }).click()
  const card = page.locator('.rigi-sequence'), scrubber = page.locator('.scrubber input'), scene = page.locator('.rigi-timetable-scene')
  expect(requests).toHaveLength(0)
  await card.getByRole('button', { name: /Cogwheel 1133/ }).click()
  await scrubber.fill('48780')
  await card.getByRole('button', { name: /Follow this train in terrain/ }).click()
  await expect(scene).toBeVisible()
  await expect(scrubber).toHaveValue('48780')
  await expect(scene).toHaveAttribute('data-progress', '0.6566329989400922')
  await expect(scene).toHaveAttribute('data-stopped', 'true')
  await expect(card).toContainText('Scheduled interpolation')
  await scrubber.fill('48840')
  await expect(scene).toHaveAttribute('data-progress', '0.6566329989400922')
  await page.screenshot({ path: info.outputPath('rigi-timed-kaltbad.png') })
  if (isMobile) {
    await page.locator('.mobile-speed-select .mobile-picker__trigger').click()
    await page.getByRole('option', { name: '1:1', exact: true }).click()
  } else await page.locator('.speed-picker').getByRole('button', { name: '1:1', exact: true }).click()
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect.poll(async () => Number(await scrubber.inputValue())).toBeGreaterThan(48840)
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await expect(scene).toHaveAttribute('data-progress', '0.6566329989400922')
  await scrubber.fill('48960')
  await expect.poll(async () => Number(await scene.getAttribute('data-progress'))).toBeGreaterThan(.69)
  await card.getByRole('button', { name: /Return to map/ }).click()
  await expect(scene).toHaveCount(0)
  await expect(scrubber).toHaveValue('48960')
  await card.getByRole('combobox', { name: 'Choose an approach' }).selectOption('weggis')
  await card.getByRole('button', { name: /Cogwheel 1139/ }).click()
  await card.getByRole('button', { name: /Follow this train in terrain/ }).click()
  await expect(scene).toBeVisible()
  await expect(scrubber).toHaveValue('52500')
  await expect(scene).toHaveAttribute('data-progress', '0.6566329989400922')
  expect(requests).toHaveLength(1)
  await scrubber.fill('49200')
  await expect(scene).toHaveCount(0)
  await expect(card).toHaveAttribute('data-phase', 'cable')
  await scrubber.fill('53210')
  await expect(scene).toBeVisible()
  await page.getByRole('button', { name: /Resume motion/i }).click()
  await expect(scrubber).toHaveValue('53220')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await expect(scene).toHaveAttribute('data-progress', '1')
  if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('terrain failure keeps the map and time usable and can be retried', async ({ page, isMobile }, info) => {
  let fail = true
  await page.route('**/vitznau-rigi-corridor.json', route => fail ? route.fulfill({ status: 503, body: 'Unavailable' }) : route.continue())
  await page.goto('/?study=rigi-lake&time=43200')
  await page.getByRole('button', { name: /Follow lake to summit/ }).click()
  const card = page.locator('.rigi-sequence'), scrubber = page.locator('.scrubber input')
  await card.getByRole('button', { name: /Cogwheel 1133/ }).click()
  await card.getByRole('button', { name: /Follow this train in terrain/ }).click()
  await expect(card).toContainText('Terrain unavailable for this service')
  await expect(scrubber).toHaveValue('47700')
  await expect(page.locator('.scene canvas')).toBeVisible()
  fail = false
  await card.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.locator('.rigi-timetable-scene')).toBeVisible()
  await expect(scrubber).toHaveValue('47700')
  await expect(card).toContainText('Scheduled interpolation')
  await expect(page.locator('.rigi-timetable-scene canvas')).toBeVisible()
  await page.waitForTimeout(1000) // Let the measured terrain camera settle for visual review.
  await page.screenshot({ path: info.outputPath('rigi-timed-retry.png') })
  if (isMobile) expect((await card.boundingBox())!.height).toBeLessThan(240)
})
