import { expect, test, type Page } from '@playwright/test'

async function openRigi(page: Page, mobile: boolean) {
  await page.goto('/')
  await expect(page.locator('.network-count-row strong').first()).not.toHaveText('—')
  if (mobile) {
    await page.locator('.mobile-study-picker .mobile-picker__trigger').click()
    await page.getByRole('option', { name: /RIGI/ }).click()
  } else await page.getByRole('button', { name: 'Explore Lake Lucerne and Rigi', exact: true }).click()
  await expect(page.locator('.network-card')).toContainText('190')
}

test('Rigi ascent loads only on entry and exposes measured ground on desktop and phone', async ({ page, isMobile }, testInfo) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', r => { if (r.url().includes('vitznau-rigi-corridor.json')) requests.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await openRigi(page, isMobile)
  expect(requests).toHaveLength(0)
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('h1')).toHaveText('Vitznau → Rigi Kulm')
  await expect(page.locator('.prototype-note')).toContainText('swissALTIRegio')
  await expect(page.locator('.rigi-terrain-profile')).toContainText('Scenic playback')
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await page.locator('.scrubber input').fill('0')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').first()).toHaveText('436')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').last()).toHaveText('0')
  await expect(page.getByRole('img', { name: 'Ground profile beneath the railway' })).toBeVisible()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.locator('.scrubber input').fill('0.55')
  await page.waitForTimeout(1000) // Settle the follow camera for visual inspection.
  await expect(page.locator('.scrubber input')).toHaveValue('0.55')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').first()).toHaveText('1268')
  await page.screenshot({ path: testInfo.outputPath('rigi-ascent.png') })
  if (isMobile) {
    const card = await page.locator('.journey-card').boundingBox(), transport = await page.locator('.transport').boundingBox()
    expect(card!.height).toBeLessThan(190)
    expect(transport!.y - card!.y - card!.height).toBeGreaterThan(230)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.locator('.scrubber input').fill('1')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').first()).toHaveText('1748')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').last()).toHaveText('1312')
  await expect(page.locator('footer a[href*="swissaltiregio"]')).toBeAttached()
  await page.getByRole('button', { name: /220 Kiental → Griesalp/ }).click()
  await expect(page.locator('h1')).toHaveText('Kiental → Griesalp')
  await expect(page.locator('.prototype-note')).toContainText('swissALTI3D')
  expect(requests).toHaveLength(1)
  expect(errors).toEqual([])
})

test('unavailable Rigi terrain stays honest and can be retried', async ({ page, isMobile }) => {
  await page.route('**/vitznau-rigi-corridor.json', r => r.fulfill({ status: 503, body: 'Unavailable' }))
  await openRigi(page, isMobile)
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('.journey-card')).toContainText('Rigi terrain unavailable')
  await expect(page.locator('.journey-card')).not.toContainText('Chur')
  await expect(page.locator('.scene canvas')).toHaveCount(0)
  await page.unroute('**/vitznau-rigi-corridor.json')
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('.rigi-terrain-profile')).toBeVisible()
})

test('a selected uphill cogwheel service enters its own terrain journey', async ({ page, isMobile }) => {
  await openRigi(page, isMobile)
  await page.locator('.train-search input').fill('1127')
  await page.getByRole('option').filter({ has: page.locator('.result-service b') }).first().click()
  await page.locator('.selected-card').getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('h1')).toHaveText('Vitznau → Rigi Kulm')
  await expect(page.locator('.rigi-terrain-profile')).toBeVisible()
  await expect(page.locator('.route-id')).toHaveText('82-1127')
  await expect(page.locator('.progress-copy')).toContainText('12:47')
})

test('the Arth-Goldau approach has separate lazy terrain and a shared summit', async ({ page, isMobile }, testInfo) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', r => { if (/\/(?:vitznau|arth-goldau)-rigi-corridor\.json/.test(r.url())) requests.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await openRigi(page, isMobile)
  expect(requests).toHaveLength(0)
  await page.getByRole('button', { name: /Climb Arth-Goldau/ }).click()
  await expect(page.locator('h1')).toHaveText('Arth-Goldau → Rigi Kulm')
  await expect(page.locator('.rigi-terrain-profile')).toContainText('Rise from Arth-Goldau')
  expect(requests).toHaveLength(1)
  expect(requests[0]).toContain('arth-goldau-rigi-corridor.json')
  await page.getByRole('button', { name: /Pause motion/i }).click()
  await page.locator('.scrubber input').fill('0')
  await expect(page.locator('.journey-card')).toContainText('Arth-Goldau RB')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').first()).toHaveText('510')
  await expect(page.locator('.route-id')).toHaveText('81-139')
  await page.locator('.scrubber input').fill('0.5')
  await page.waitForTimeout(1000)
  await expect(page.locator('.scrubber input')).toHaveValue('0.5')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('arth-goldau-ascent.png') })
  if (isMobile) {
    const card = await page.locator('.journey-card').boundingBox(), transport = await page.locator('.transport').boundingBox()
    expect(card!.height).toBeLessThan(190)
    expect(transport!.y - card!.y - card!.height).toBeGreaterThan(230)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.locator('.scrubber input').fill('1')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').first()).toHaveText('1748')
  await expect(page.locator('.rigi-terrain-profile .metric-grid strong').last()).toHaveText('1239')
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('h1')).toHaveText('Vitznau → Rigi Kulm')
  await expect(page.locator('.rigi-terrain-profile')).toContainText('Rise from Vitznau')
  await expect(page.locator('.route-id')).toHaveText('82-1127')
  expect(requests).toHaveLength(2)
  expect(errors).toEqual([])
})

test('an unavailable Arth-Goldau approach can switch to Vitznau without showing the wrong terrain', async ({ page, isMobile }) => {
  await page.route('**/arth-goldau-rigi-corridor.json', r => r.fulfill({ status: 503, body: 'Unavailable' }))
  await openRigi(page, isMobile)
  await page.getByRole('button', { name: /Climb Arth-Goldau/ }).click()
  await expect(page.locator('.journey-card')).toContainText('Rigi terrain unavailable')
  await expect(page.locator('.journey-card')).toContainText('Arth-Goldau → Rigi Kulm')
  await expect(page.locator('.journey-card')).not.toContainText('Vitznau')
  await expect(page.locator('.scene canvas')).toHaveCount(0)
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('.rigi-terrain-profile')).toContainText('Rise from Vitznau')
})

test('a selected Arth-Goldau service retains its own scheduled stops', async ({ page, isMobile }) => {
  await openRigi(page, isMobile)
  await page.locator('.train-search input').fill('145')
  await page.getByRole('option').filter({ has: page.locator('.result-service b') }).first().click()
  await page.locator('.selected-card').getByRole('button', { name: /Climb Arth-Goldau/ }).click()
  await expect(page.locator('.rigi-terrain-profile')).toBeVisible()
  await expect(page.locator('h1')).toHaveText('Arth-Goldau → Rigi Kulm')
  await expect(page.locator('.route-id')).toHaveText('81-145')
  await expect(page.locator('.progress-copy')).toContainText('13:34')
  await page.getByRole('button', { name: /Climb Vitznau/ }).click()
  await expect(page.locator('.route-id')).toHaveText('82-1127')
})
