import { expect, test } from '@playwright/test'

test('Rigi connections guide selects both approaches, distinct interchanges and the shared summit', async ({ page, isMobile }, info) => {
  const loaded: string[] = [], errors: string[] = []
  page.on('request', r => { if (r.url().includes('RigiGuide') || r.url().includes('-corridor.json')) loaded.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/?study=rigi-lake&time=43200')
  const opener = page.getByRole('button', { name: 'Explore the Rigi connections →', exact: true }), dialog = page.getByRole('dialog')
  await expect(opener).toBeVisible()
  expect(loaded).toHaveLength(0)
  const pause = page.getByRole('button', { name: /Pause motion/i })
  if (await pause.isVisible()) await pause.click()
  await page.locator('.scrubber input').fill('43200')
  await opener.click()
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.rigi-guide-stop')).toHaveCount(11)
  await expect(dialog.locator('path')).toHaveCount(12)
  await expect(dialog).toContainText('schematic, not to scale')
  await page.screenshot({ path: info.outputPath('rigi-connections.png') })
  for (const [id, name] of [['arth', 'Arth-Goldau RB'], ['staffel', 'Rigi Staffel'], ['kulm', 'Rigi Kulm'], ['kaltbadRail', 'Rigi Kaltbad-First'], ['kaltbadCable', 'Rigi Kaltbad (Luftseilbahn)'], ['weggisCable', 'Weggis (Luftseilbahn)'], ['weggisPier', 'Weggis'], ['vitznau', 'Vitznau'], ['luzern', 'Luzern Bahnhofquai']]) {
    await dialog.locator(`[data-stop="${id}"]`).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.locator('.station-card .service')).toHaveText(name)
    await expect(page.locator('.scrubber input')).toHaveValue('43200')
    await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
    await opener.click()
  }
  await dialog.locator('summary').click()
  await expect(dialog).toContainText('not walking routes')
  await expect(dialog.locator('a')).toHaveAttribute('href', './methodology.html#rigi-connections')
  await dialog.getByRole('button', { name: 'Close Rigi connections' }).click()
  await expect(opener).toBeFocused()
  await opener.click()
  await dialog.locator('[data-stop="kulm"]').focus()
  await page.keyboard.press('Space') // Must activate the station without toggling the map's playback shortcut.
  await expect(page.locator('.station-card .service')).toHaveText('Rigi Kulm')
  await expect(page.getByRole('button', { name: /Resume motion/i })).toBeVisible()
  await opener.click()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(opener).toBeFocused()
  if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(loaded.every(url => !url.includes('-corridor.json'))).toBe(true)
  expect(errors).toEqual([])
})
