import {expect,test} from '@playwright/test'
test('Rochers-de-Naye loads on request and follows full summit trains with actual dwells',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('rochers-day.json'))requests++})
 await page.goto('/');await expect(page.getByRole('button',{name:'Explore studies',exact:true})).toBeVisible();expect(requests).toBe(0)
 await page.getByRole('button',{name:'Explore studies',exact:true}).click()
 await page.getByRole('dialog').getByRole('button').filter({hasText:'Montreux → Rochers-de-Naye'}).click()
 await expect(page.getByRole('heading',{name:'Montreux → Rochers-de-Naye',exact:true})).toBeVisible()
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('rochers-map.png')})
 await page.getByRole('button',{name:/Follow Montreux to Rochers-de-Naye/}).click()
 const card=page.locator('.rochers-journey'),clock=page.locator('.scrubber input')
 await expect(card).toHaveAttribute('data-phase','rail');await expect(clock).toHaveValue('41640');expect(requests).toBe(1)
 if(isMobile)await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await expect(card.getByRole('combobox',{name:'Choose a departure'}).locator('option')).toHaveCount(10)
 await expect(card.locator('nav button')).toHaveCount(16)
 await card.locator('nav button').filter({has:page.getByText('Caux',{exact:true})}).click();await expect(clock).toHaveValue('42960')
 await expect(card.locator('nav button[aria-current]')).toContainText('11:56 → 11:58')
 await expect(card).toContainText('The day map includes shorter services')
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('rochers-journey.png')})
 await clock.fill('44510');await page.getByRole('button',{name:/Resume motion/}).click();await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Rochers-de-Naye')
 await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 await card.getByRole('button',{name:/Replay journey/}).click();await expect(clock).toHaveValue('41640')
 if(isMobile)await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent');await expect(clock).toHaveValue('44820')
 await expect(card.getByRole('heading')).toHaveText('Rochers-de-Naye → Montreux')
 await expect(card.locator('nav button strong').first()).toHaveText('Rochers-de-Naye');await expect(card.locator('nav button strong').last()).toHaveText('Montreux')
 await card.locator('nav button').filter({has:page.getByText('Glion',{exact:true})}).click();await expect(clock).toHaveValue('47400')
 await expect(card.locator('nav button[aria-current]')).toContainText('13:10 → 13:11')
 await clock.fill('48230');await page.getByRole('button',{name:/Resume motion/}).click();await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Montreux')
 await card.getByRole('button',{name:'Exit journey',exact:true}).click()
 await page.locator('.train-search input').fill('Glion-Collège');await expect(page.getByRole('option').first()).toBeVisible()
 if(isMobile){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.mobile-study-picker .mobile-picker__trigger')).toContainText('RDN')}
 expect(errors).toEqual([])
})
test('Rochers retry and dated station links preserve time and explain unavailable dates',async({page})=>{
 let fail=true;await page.route('**/rochers-day.json',r=>fail?r.fulfill({status:503,body:'unavailable'}):r.continue())
 await page.goto('/?study=rochers&date=2026-09-04&time=42420&station=Glion-Coll%C3%A8ge')
 await expect(page.getByText('Rochers-de-Naye is unavailable. Retry or choose another study.')).toBeVisible()
 fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click()
 await expect(page.locator('.station-card .service')).toHaveText('Glion-Collège');await expect(page.locator('.scrubber input')).toHaveValue('42420')
 await page.goto('/?study=rochers&date=2026-09-14&time=43200')
 await expect(page.getByText('The linked date is unavailable; showing the available timetable.')).toBeVisible()
})
