import { expect, test } from '@playwright/test'

test('Rochers terrain preserves actual calls through outdoor, tunnel and gallery sections in both directions', async ({ page, isMobile }, info) => {
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); let requests = 0
 page.on('request', r => { if (r.url().includes('rochers-ascent-terrain.json')) requests++ })
 await page.goto('/?study=rochers'); await page.getByRole('button', { name: /Follow Montreux to Rochers-de-Naye/ }).click()
 const card = page.locator('.rochers-journey'), clock = page.locator('.scrubber input'), scene = page.locator('.rochers-terrain-scene'), status = card.locator('[data-terrain-status]')
 await expect(clock).toHaveValue('41640'); expect(requests).toBe(0)
 await card.getByRole('button', { name: 'Follow in measured terrain', exact: true }).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'tunnel'); await expect(scene).toHaveCount(0); expect(requests).toBe(1)
 await card.getByRole('button', { name: 'Journey details', exact: true }).click()
 await card.locator('nav button').filter({ has: page.getByText('Caux', { exact: true }) }).click()
 await expect(clock).toHaveValue('42960'); await expect(scene).toHaveAttribute('data-rendered', 'true'); await expect(scene).toHaveAttribute('data-stopped', 'true')
 await page.screenshot({ path: info.outputPath('rochers-caux-terrain.png') })
 await clock.fill('43620'); await page.getByRole('button', { name: /Resume motion/ }).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'covered'); await expect(scene).toHaveCount(0)
 await expect(page.getByRole('button', { name: /Pause motion/ })).toBeVisible(); await page.getByRole('button', { name: /Pause motion/ }).click()
 await clock.fill('43700'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await page.screenshot({ path: info.outputPath('rochers-ascent-terrain.png') })
 await clock.fill('44200'); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel'); await expect(scene).toHaveCount(0)
 await clock.fill('44510'); await page.getByRole('button', { name: /Resume motion/ }).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(card).toContainText('Arrived · Rochers-de-Naye')
 await card.getByRole('button', { name: /Replay journey/ }).click(); await expect(clock).toHaveValue('41640')
 await card.getByRole('button', { name: 'Journey details', exact: true }).click()
 await card.getByRole('combobox', { name: 'Direction', exact: true }).selectOption('descent')
 await expect(clock).toHaveValue('44820'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await card.getByRole('button', { name: 'Journey details', exact: true }).click()
 await clock.fill('44860'); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel'); await expect(scene).toHaveCount(0)
 await clock.fill('45450'); await expect(status).toHaveAttribute('data-terrain-status', 'covered')
 await clock.fill('46000'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await page.screenshot({ path: info.outputPath('rochers-descent-terrain.png') })
 await card.getByRole('button', { name: 'Return to map', exact: true }).click(); await expect(scene).toHaveCount(0); await expect(clock).toHaveValue('46000')
 await card.getByRole('button', { name: 'Follow in measured terrain', exact: true }).click(); await expect(scene).toHaveAttribute('data-rendered', 'true'); expect(requests).toBe(1)
 await card.getByRole('button', { name: 'Journey details', exact: true }).click()
 await card.locator('nav button').filter({ has: page.getByText('Glion', { exact: true }) }).click()
 await expect(clock).toHaveValue('47400'); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel')
 await clock.fill('48230'); await page.getByRole('button', { name: /Resume motion/ }).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(card).toContainText('Arrived · Montreux')
 await expect(page.getByRole('button', { name: /Resume motion/ })).toBeVisible()
 await card.getByRole('button', { name: 'Exit journey', exact: true }).click(); await expect(scene).toHaveCount(0)
 if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 expect(errors).toEqual([])
})

test('Rochers terrain retries request failure and rejects unlisted downhill journeys', async ({ page }) => {
 let fail = true, omitDownhill = false
 await page.route('**/rochers-ascent-terrain.json', async route => {
  if (fail) return route.fulfill({ status: 503, body: 'unavailable' })
  const response = await route.fetch(), data = await response.json()
  if (omitDownhill) delete data.routes[0].reverseTripIds
  await route.fulfill({ response, json: data })
 })
 await page.goto('/?study=rochers'); await page.getByRole('button', { name: /Follow Montreux to Rochers-de-Naye/ }).click()
 const card = page.locator('.rochers-journey'), clock = page.locator('.scrubber input'), status = card.locator('[data-terrain-status]')
 await expect(card).toHaveAttribute('data-phase', 'rail'); await expect(clock).toHaveValue('41640')
 await clock.fill('43000'); await card.getByRole('button', { name: 'Follow in measured terrain', exact: true }).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(clock).toHaveValue('43000')
 fail = false; await card.getByRole('button', { name: 'Retry terrain', exact: true }).click()
 await expect(page.locator('.rochers-terrain-scene')).toHaveAttribute('data-rendered', 'true'); await expect(clock).toHaveValue('43000')
 omitDownhill = true; await page.reload(); await page.getByRole('button', { name: /Follow Montreux to Rochers-de-Naye/ }).click()
 await card.getByRole('button', { name: 'Follow in measured terrain', exact: true }).click(); await expect(status).toHaveAttribute('data-terrain-status', 'tunnel')
 await card.getByRole('button', { name: 'Journey details', exact: true }).click(); await card.getByRole('combobox', { name: 'Direction', exact: true }).selectOption('descent')
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(page.locator('.rochers-terrain-scene')).toHaveCount(0)
 omitDownhill = false; await card.getByRole('button', { name: 'Retry terrain', exact: true }).click()
 await expect(page.locator('.rochers-terrain-scene')).toHaveAttribute('data-rendered', 'true'); await expect(clock).toHaveValue('44820')
})
