import {expect, test} from '@playwright/test'

test('funicular terrain follows both directions and returns to the map at unresolved sections', async ({page, isMobile}, info) => {
 const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
 let requests = 0; page.on('request', r => {if (r.url().includes('territet-ascent-terrain.json')) requests++})
 await page.goto('/?study=territet&date=2026-09-04')
 await page.getByRole('button', {name: 'Follow the Territet–Glion funicular', exact: false}).click()
 const card = page.locator('.territet-journey'), clock = page.locator('.scrubber input'), scene = page.locator('.territet-terrain-scene'), status = card.locator('[data-terrain-status]')
 await expect(clock).toHaveValue('43440'); expect(requests).toBe(0)
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(status).toContainText('Rail and ground heights differ'); await expect(scene).toHaveCount(0)
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await expect(card.getByRole('combobox', {name: 'Choose a departure'}).locator('option')).toHaveCount(70)
 await card.locator('nav button').filter({hasText: 'Collonge (funi)'}).click()
 await expect(clock).toHaveValue('43500'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await expect(scene).toHaveAttribute('data-context-tracks', '2'); await expect(scene).toHaveAttribute('data-stopped', 'true')
 await page.screenshot({path: info.outputPath('territet-collonge-terrain.png')})
 await card.getByRole('button', {name: 'Return to map', exact: true}).click(); await expect(scene).toHaveCount(0); await expect(clock).toHaveValue('43500')
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click(); await expect(scene).toHaveAttribute('data-rendered', 'true'); expect(requests).toBe(1)
 await clock.fill('43560'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(status).toContainText('Passing loop'); await expect(scene).toHaveCount(0)
 await expect(page.getByRole('button', {name: /Pause motion/})).toBeVisible()
 await page.getByRole('button', {name: /Pause motion/}).click()
 await clock.fill('43650'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await page.screenshot({path: info.outputPath('territet-upper-terrain.png')})
 await clock.fill('43790'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(scene).toHaveCount(0)
 await card.getByRole('button', {name: /Replay journey/}).click(); await expect(clock).toHaveValue('43440')
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.getByRole('combobox', {name: 'Direction', exact: true}).selectOption('descent')
 await expect(clock).toHaveValue('43440'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await page.screenshot({path: info.outputPath('territet-downhill-terrain.png')})
 await clock.fill('43560'); await expect(status).toContainText('Passing loop'); await expect(scene).toHaveCount(0)
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.locator('nav button').filter({hasText: 'Collonge (funi)'}).click()
 await expect(clock).toHaveValue('43620'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await clock.fill('43790'); await page.getByRole('button', {name: /Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase', 'complete'); await expect(page.getByRole('button', {name: /Resume motion/})).toBeVisible()
 await card.getByRole('button', {name: 'Journey details', exact: true}).click()
 await card.getByRole('combobox', {name: 'Choose a departure'}).selectOption({index: 0})
 await expect(clock).toHaveValue('18240'); await expect(scene).toHaveAttribute('data-rendered', 'true')
 await card.getByRole('button', {name: 'Exit journey', exact: true}).click(); await expect(scene).toHaveCount(0)
 expect(requests).toBe(1); expect(errors).toEqual([])
 if (isMobile) expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('funicular terrain retries download and invalid branch data without changing the clock', async ({page}) => {
 let mode = 'failed'
 await page.route('**/territet-ascent-terrain.json', async route => {
  if (mode === 'failed') return route.fulfill({status: 503, body: 'unavailable'})
  const response = await route.fetch(), data = await response.json()
  if (mode === 'unreviewed') data.contextTracks.pop()
  await route.fulfill({response, json: data})
 })
 await page.goto('/?study=territet&date=2026-09-04')
 await page.getByRole('button', {name: 'Follow the Territet–Glion funicular', exact: false}).click()
 const card = page.locator('.territet-journey'), clock = page.locator('.scrubber input'), scene = page.locator('.territet-terrain-scene'), status = card.locator('[data-terrain-status]')
 await expect(card).toHaveAttribute('data-phase', 'rail'); await expect(clock).toHaveValue('43440')
 await clock.fill('43500'); await expect(clock).toHaveValue('43500')
 await card.getByRole('button', {name: 'Follow in measured terrain', exact: true}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(clock).toHaveValue('43500')
 mode = 'unreviewed'; await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect(status).toHaveAttribute('data-terrain-status', 'error'); await expect(scene).toHaveCount(0); await expect(clock).toHaveValue('43500')
 mode = 'valid'; await card.getByRole('button', {name: 'Retry terrain', exact: true}).click()
 await expect(scene).toHaveAttribute('data-rendered', 'true'); await expect(clock).toHaveValue('43500')
 await page.locator('.train-search input').fill('Collonge')
 await page.getByRole('option').filter({has: page.locator('.result-service', {hasText: /^Collonge \(funi\)$/})}).click()
 await expect(card).toHaveCount(0); await expect(scene).toHaveCount(0); await expect(page.locator('.station-card .service')).toHaveText('Collonge (funi)')
})
