import {expect,test} from '@playwright/test'

test('Territet–Glion loads on demand and follows all three dated calls in either direction',async({page,isMobile},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let requests=0
 page.on('request',r=>{if(r.url().includes('territet-day.json'))requests++})
 await page.goto('/');await expect(page.getByRole('button',{name:'Explore studies',exact:true})).toBeVisible();expect(requests).toBe(0)
 await page.getByRole('button',{name:'Explore studies',exact:true}).click()
 await page.getByRole('dialog').getByRole('button').filter({hasText:'Territet → Glion'}).click()
 await expect(page.getByRole('heading',{name:'Territet → Glion',exact:true})).toBeVisible()
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('territet-map.png')})
 await page.getByRole('button',{name:/Follow the Territet–Glion funicular/}).click()
 const card=page.locator('.territet-journey'),clock=page.locator('.scrubber input')
 await expect(card).toHaveAttribute('data-phase','rail');await expect(clock).toHaveValue('43440');expect(requests).toBe(1)
 if(isMobile)await card.getByRole('button',{name:'Journey details',exact:true}).click()
 const departures=card.getByRole('combobox',{name:'Choose a departure'})
 await expect(departures.locator('option')).toHaveCount(70);await expect(card.locator('nav button')).toHaveCount(3)
 await card.locator('nav button').filter({hasText:'Collonge (funi)'}).click();await expect(clock).toHaveValue('43500')
 await expect(card.locator('nav button[aria-current]')).toContainText('12:05')
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('territet-journey.png')})
 await clock.fill('43790');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Glion (funi)')
 await card.getByRole('button',{name:/Replay journey/}).click();await expect(clock).toHaveValue('43440')
 if(isMobile)await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await card.getByRole('combobox',{name:'Direction',exact:true}).selectOption('descent')
 await expect(card.getByRole('heading')).toHaveText('Glion → Territet');await expect(clock).toHaveValue('43440')
 await card.locator('nav button').filter({hasText:'Collonge (funi)'}).click();await expect(clock).toHaveValue('43620')
 await expect(card.locator('nav button[aria-current]')).toContainText('12:07')
 await clock.fill('43790');await page.getByRole('button',{name:/Resume motion/}).click()
 await expect(card).toHaveAttribute('data-phase','complete');await expect(card).toContainText('Arrived · Territet (funi)')
 await expect(page.getByRole('button',{name:/Resume motion/})).toBeVisible()
 if(isMobile)await card.getByRole('button',{name:'Journey details',exact:true}).click()
 await departures.selectOption({index:0});await expect(clock).toHaveValue('18240')
 await card.getByRole('button',{name:'Exit journey',exact:true}).click()
 await page.locator('.train-search input').fill('Collonge');await expect(page.getByRole('option').first()).toBeVisible()
 if(isMobile){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.mobile-study-picker .mobile-picker__trigger')).toContainText('TG')}
 expect(errors).toEqual([])
})

test('Territet retry preserves its dated station link and explains unavailable dates',async({page})=>{
 let fail=true;await page.route('**/territet-day.json',r=>fail?r.fulfill({status:503,body:'unavailable'}):r.continue())
 await page.goto('/?study=territet&date=2026-09-04&time=43500&station=Collonge%20(funi)')
 await expect(page.getByText('Territet–Glion is unavailable. Retry or choose another study.')).toBeVisible()
 fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click()
 await expect(page.locator('.station-card .service')).toHaveText('Collonge (funi)');await expect(page.locator('.scrubber input')).toHaveValue('43500')
 await page.goto('/?study=territet&date=2026-09-05&time=43500')
 await expect(page.getByText('The linked date is unavailable; showing the available timetable.')).toBeVisible()
})
