import { test, expect } from '@playwright/test'

test('Ticino loads lazily, preserves date shares, searches and changes the full day', async ({ page }, testInfo) => {
  const requests:string[]=[]
  page.on('request',r=>requests.push(r.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(u=>u.includes('/ticino-region/'))).toBe(false)
  await page.getByRole('button',{name:'Explore studies',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/Ticino · rail and valley buses/}).click()
  await expect(page.locator('.network-card .between')).toContainText('Full day')
  await expect(page.locator('.scrubber input')).toHaveAttribute('max','86400')
  await expect(page.getByLabel('Ticino timetable date')).toHaveValue('2026-09-04')
  await expect(page.locator('.explore-status').filter({hasText:'Partial canton coverage · initial rail and bus scope'})).toContainText('2026-09-04')
  // Allow the map camera to settle after switching from the national overview.
  await page.waitForTimeout(1500)
  await page.screenshot({path:testInfo.outputPath('ticino-overview.png')})
  await page.getByLabel('Ticino timetable date').selectOption('2026-09-06')
  await expect(page.locator('.explore-status').filter({hasText:'Partial canton coverage · initial rail and bus scope'})).toContainText('2026-09-06')
  await expect(page.locator('.network-card .between')).toContainText('Full day')
  const search=page.locator('.train-search input[type=search]')
  await search.fill('Lugano')
  await page.locator('.search-results .station-result').first().click()
  await expect(page.locator('.station-card')).toContainText('Lugano')
  await page.locator('.scrubber input').fill('62100')
  await expect.poll(()=>requests.some(u=>u.includes('ticino-region/2026-09-06/day-chunks/16-18'))).toBe(true)
  await page.getByRole('button',{name:'Share study',exact:true}).click()
  const url=await page.getByRole('textbox',{name:'Copy this link',exact:true}).inputValue()
  expect(url).toContain('study=ticino-region');expect(url).toContain('date=2026-09-06')
  await page.goto(url)
  await expect(page.getByLabel('Ticino timetable date')).toHaveValue('2026-09-06')
  await expect(page.locator('.station-card')).toContainText('Lugano')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('ticino-sunday-share.png')})
})

test('Ticino retries a morning fixture and labels its admitted modes',async({page},testInfo)=>{
  let fail=true
  await page.route('**/ticino-region/2026-09-04/ticino-region-morning.json',r=>fail?r.fulfill({status:503,body:''}):r.continue())
  await page.goto('/?study=ticino-region&range=morning')
  await expect(page.getByRole('button',{name:'Retry',exact:true})).toBeVisible()
  fail=false
  await page.getByRole('button',{name:'Retry',exact:true}).click()
  await expect(page.locator('.network-card .between')).toContainText('Selected trains and buses')
  await expect(page.locator('.scene canvas')).toBeVisible()
  const attribution=page.locator('a[href$="ticino-region/sources.json"]').first()
  await expect(attribution).toContainText('FOT')
  await expect(attribution).toContainText('OpenStreetMap contributors')
  await expect(attribution).toContainText('ODbL')
  await page.screenshot({path:testInfo.outputPath('ticino-morning.png')})
})
