import type { UiLanguage } from '../i18n.ts'

const en = {
  title: 'Aargau road surveys', intro: 'Daily averages, survey periods and report notes',
  note: 'Survey statistics, not traffic on a selected day. Directional totals and separate surveys are shown individually.',
  station: 'Counter', year: 'Reference year', survey: 'Survey and direction', both: 'Both directions', direction: 'Direction',
  annual: 'Estimated annual daily average', period: 'Daily average over the survey', unit: 'vehicles per day',
  missing: 'Not reported', withheld: 'Withheld', missingPeriod: 'Survey dates not reported', invalidPeriod: 'Invalid survey dates in the source. Period averages are withheld.',
  until: 'to', exclusive: 'end excluded', loading: 'Loading road surveys…', error: 'Road surveys could not be loaded.', retry: 'Try again',
  unreviewed: 'Report notes have not been checked. The averages may include adjustments.',
  substitution: 'Holiday adjustment: data for {date} were replaced with data for {replacement}.',
  latest: 'Marked by the publisher as the latest plausible survey; this does not guarantee recent data.',
  details: 'Other averages', metric: 'Measure', value: 'Vehicles', report: 'Open source reports', source: 'Source', acquired: 'Downloaded',
  weekday: 'Weekday daily average', daytime: 'Daytime average, 06:00–22:00', nighttime: 'Nighttime average, 22:00–06:00',
  morning: 'Average weekday peak, 07:00–08:00', evening: 'Average weekday peak, 17:00–18:00', owner: 'Counter owner',
}
export const AARGAU_STATISTIC_COPY: Record<UiLanguage, typeof en> = {
  en,
  de: {
    title: 'Aargauer Verkehrszählungen', intro: 'Tagesmittel, Erhebungszeiträume und Berichtshinweise',
    note: 'Statistische Mittelwerte, kein Verkehr eines ausgewählten Tages. Richtungen und separate Erhebungen werden einzeln angezeigt.',
    station: 'Zählstelle', year: 'Bezugsjahr', survey: 'Erhebung und Richtung', both: 'Beide Richtungen', direction: 'Richtung',
    annual: 'Geschätztes Jahresmittel pro Tag', period: 'Tagesmittel im Erhebungszeitraum', unit: 'Fahrzeuge pro Tag',
    missing: 'Nicht angegeben', withheld: 'Nicht angezeigt', missingPeriod: 'Erhebungsdaten nicht angegeben', invalidPeriod: 'Ungültige Erhebungsdaten in der Quelle. Zeitraumbezogene Mittelwerte werden nicht angezeigt.',
    until: 'bis', exclusive: 'Ende exklusiv', loading: 'Verkehrszählungen werden geladen…', error: 'Verkehrszählungen konnten nicht geladen werden.', retry: 'Erneut versuchen',
    unreviewed: 'Berichtshinweise wurden noch nicht geprüft. Die Mittelwerte können Anpassungen enthalten.',
    substitution: 'Feiertagsanpassung: Die Daten vom {date} wurden durch Daten vom {replacement} ersetzt.',
    latest: 'Vom Herausgeber als letzte plausible Zählung markiert; dies garantiert keine aktuellen Daten.',
    details: 'Weitere Mittelwerte', metric: 'Kennzahl', value: 'Fahrzeuge', report: 'Quellberichte öffnen', source: 'Quelle', acquired: 'Heruntergeladen',
    weekday: 'Tagesmittel an Werktagen', daytime: 'Tageszeitmittel, 06:00–22:00', nighttime: 'Nachtmittel, 22:00–06:00',
    morning: 'Mittlere Werktagsspitze, 07:00–08:00', evening: 'Mittlere Werktagsspitze, 17:00–18:00', owner: 'Eigentümer der Zählstelle',
  },
  fr: {
    title: 'Comptages routiers en Argovie', intro: 'Moyennes journalières, périodes et notes des rapports',
    note: 'Statistiques de comptage, pas le trafic d’une journée choisie. Les directions et les enquêtes distinctes sont affichées séparément.',
    station: 'Compteur', year: 'Année de référence', survey: 'Enquête et direction', both: 'Les deux directions', direction: 'Direction',
    annual: 'Moyenne journalière annuelle estimée', period: 'Moyenne journalière sur la période', unit: 'véhicules par jour',
    missing: 'Non renseigné', withheld: 'Non affiché', missingPeriod: 'Dates de comptage non renseignées', invalidPeriod: 'Dates de comptage invalides dans la source. Les moyennes de période ne sont pas affichées.',
    until: 'au', exclusive: 'fin exclue', loading: 'Chargement des comptages…', error: 'Impossible de charger les comptages.', retry: 'Réessayer',
    unreviewed: 'Les notes du rapport n’ont pas été vérifiées. Les moyennes peuvent inclure des ajustements.',
    substitution: 'Ajustement de jour férié : les données du {date} ont été remplacées par celles du {replacement}.',
    latest: 'Dernier comptage plausible selon l’éditeur ; cela ne garantit pas des données récentes.',
    details: 'Autres moyennes', metric: 'Indicateur', value: 'Véhicules', report: 'Ouvrir les rapports sources', source: 'Source', acquired: 'Téléchargé le',
    weekday: 'Moyenne journalière des jours ouvrables', daytime: 'Moyenne de jour, 06:00–22:00', nighttime: 'Moyenne de nuit, 22:00–06:00',
    morning: 'Pointe moyenne des jours ouvrables, 07:00–08:00', evening: 'Pointe moyenne des jours ouvrables, 17:00–18:00', owner: 'Propriétaire du compteur',
  },
  it: {
    title: 'Conteggi stradali in Argovia', intro: 'Medie giornaliere, periodi e note dei rapporti',
    note: 'Statistiche dei rilevamenti, non il traffico di un giorno selezionato. Direzioni e rilevamenti distinti sono mostrati separatamente.',
    station: 'Contatore', year: 'Anno di riferimento', survey: 'Rilevamento e direzione', both: 'Entrambe le direzioni', direction: 'Direzione',
    annual: 'Media giornaliera annua stimata', period: 'Media giornaliera del periodo', unit: 'veicoli al giorno',
    missing: 'Non indicato', withheld: 'Non mostrato', missingPeriod: 'Date del rilevamento non indicate', invalidPeriod: 'Date del rilevamento non valide nella fonte. Le medie del periodo non sono mostrate.',
    until: 'al', exclusive: 'fine esclusa', loading: 'Caricamento dei conteggi…', error: 'Impossibile caricare i conteggi.', retry: 'Riprova',
    unreviewed: 'Le note del rapporto non sono state verificate. Le medie possono includere correzioni.',
    substitution: 'Correzione per festività: i dati del {date} sono stati sostituiti con quelli del {replacement}.',
    latest: 'Indicato dall’editore come ultimo rilevamento plausibile; ciò non garantisce dati recenti.',
    details: 'Altre medie', metric: 'Indicatore', value: 'Veicoli', report: 'Apri i rapporti originali', source: 'Fonte', acquired: 'Scaricato il',
    weekday: 'Media giornaliera feriale', daytime: 'Media diurna, 06:00–22:00', nighttime: 'Media notturna, 22:00–06:00',
    morning: 'Punta media feriale, 07:00–08:00', evening: 'Punta media feriale, 17:00–18:00', owner: 'Proprietario del contatore',
  },
}
