import type { UiLanguage } from '../i18n.ts'
const en = {
  title: 'Geneva & Luzern road statistics', intro: 'Annual summaries and a typical weekday profile',
  region: 'Region', geneva: 'Geneva', luzern: 'Luzern', counter: 'Counter', direction: 'Direction', both: 'Both directions', from: 'From Wolhusen', to: 'Towards Wolhusen',
  note: 'Statistical averages, not traffic observed on a selected day.', daily: 'Daily average', working: 'Working-day average', unit: 'vehicles per day', year: 'Reference year', unknownYear: 'Reference year not reported', missing: 'Not reported',
  morning: 'Morning peak', evening: 'Evening peak', peakNote: 'Peak summaries: their reference period is not specified. They are not dated hourly observations.',
  availability: 'Source availability', profile: 'Typical weekday · vehicles per hour', period: 'Report period',
  scope: 'One reviewed profile: Wolhusen Bahnhof, counter 266. This is not coverage of all Luzern counters.',
  discrepancy: 'The map lists {map} vehicles/day without a reference year; the report gives {report} for this period. The discrepancy is unresolved.',
  rounded: 'Combined and directional values are rounded separately in the report. They may differ by one vehicle when added.',
  table: 'Hourly profile values', hour: 'Hour', vehicles: 'Vehicles per hour', source: 'Source', acquired: 'Downloaded',
  loading: 'Loading statistics…', error: 'Statistics could not be loaded.', retry: 'Try again',
  allYear: '365 days/year', threeWeeks: '3 weeks/year', fiveYears: 'Once every 5 years', suspended: 'Suspended', onRequest: 'On request', unavailable: 'Unavailable',
}
export const SUMMARY_COPY: Record<UiLanguage, typeof en> = {
  en,
  de: {
    title: 'Verkehrsstatistik Genf & Luzern', intro: 'Jahresmittel und ein typisches Werktagsprofil',
    region: 'Region', geneva: 'Genf', luzern: 'Luzern', counter: 'Zählstelle', direction: 'Richtung', both: 'Beide Richtungen', from: 'Von Wolhusen', to: 'Nach Wolhusen',
    note: 'Statistische Mittelwerte, kein beobachteter Verkehr eines ausgewählten Tages.', daily: 'Tagesmittel', working: 'Werktagsmittel', unit: 'Fahrzeuge pro Tag', year: 'Bezugsjahr', unknownYear: 'Bezugsjahr nicht angegeben', missing: 'Nicht angegeben',
    morning: 'Morgenspitze', evening: 'Abendspitze', peakNote: 'Spitzenwerte ohne angegebenen Bezugszeitraum. Dies sind keine datierten Stundenmessungen.',
    availability: 'Verfügbarkeit laut Quelle', profile: 'Typischer Werktag · Fahrzeuge pro Stunde', period: 'Berichtszeitraum',
    scope: 'Ein geprüftes Profil: Wolhusen Bahnhof, Zählstelle 266. Es deckt nicht alle Luzerner Zählstellen ab.',
    discrepancy: 'Die Karte nennt {map} Fahrzeuge/Tag ohne Bezugsjahr; der Bericht nennt {report} für diesen Zeitraum. Die Abweichung ist ungeklärt.',
    rounded: 'Gesamt- und Richtungswerte sind im Bericht getrennt gerundet. Ihre Summe kann um ein Fahrzeug abweichen.',
    table: 'Stündliche Profilwerte', hour: 'Stunde', vehicles: 'Fahrzeuge pro Stunde', source: 'Quelle', acquired: 'Heruntergeladen',
    loading: 'Statistik wird geladen…', error: 'Statistik konnte nicht geladen werden.', retry: 'Erneut versuchen',
    allYear: '365 Tage/Jahr', threeWeeks: '3 Wochen/Jahr', fiveYears: 'Einmal in 5 Jahren', suspended: 'Ausgesetzt', onRequest: 'Auf Anfrage', unavailable: 'Nicht verfügbar',
  },
  fr: {
    title: 'Statistiques routières Genève & Lucerne', intro: 'Moyennes annuelles et profil d’un jour ouvrable type',
    region: 'Région', geneva: 'Genève', luzern: 'Lucerne', counter: 'Compteur', direction: 'Direction', both: 'Les deux directions', from: 'Depuis Wolhusen', to: 'Vers Wolhusen',
    note: 'Moyennes statistiques, pas le trafic observé d’une journée choisie.', daily: 'Moyenne journalière', working: 'Moyenne des jours ouvrables', unit: 'véhicules par jour', year: 'Année de référence', unknownYear: 'Année de référence non renseignée', missing: 'Non renseigné',
    morning: 'Pointe du matin', evening: 'Pointe du soir', peakNote: 'La période de référence des pointes n’est pas précisée. Ce ne sont pas des observations horaires datées.',
    availability: 'Disponibilité selon la source', profile: 'Jour ouvrable type · véhicules par heure', period: 'Période du rapport',
    scope: 'Un profil vérifié : Wolhusen Bahnhof, compteur 266. Il ne couvre pas tous les compteurs lucernois.',
    discrepancy: 'La carte indique {map} véhicules/jour sans année de référence ; le rapport indique {report} pour cette période. L’écart reste inexpliqué.',
    rounded: 'Les totaux et les valeurs directionnelles sont arrondis séparément. Leur somme peut différer d’un véhicule.',
    table: 'Valeurs horaires du profil', hour: 'Heure', vehicles: 'Véhicules par heure', source: 'Source', acquired: 'Téléchargé le',
    loading: 'Chargement des statistiques…', error: 'Impossible de charger les statistiques.', retry: 'Réessayer',
    allYear: '365 jours/an', threeWeeks: '3 semaines/an', fiveYears: 'Une fois tous les 5 ans', suspended: 'Suspendu', onRequest: 'Sur demande', unavailable: 'Indisponible',
  },
  it: {
    title: 'Statistiche stradali Ginevra e Lucerna', intro: 'Medie annuali e profilo di un giorno feriale tipico',
    region: 'Regione', geneva: 'Ginevra', luzern: 'Lucerna', counter: 'Contatore', direction: 'Direzione', both: 'Entrambe le direzioni', from: 'Da Wolhusen', to: 'Verso Wolhusen',
    note: 'Medie statistiche, non il traffico osservato di un giorno selezionato.', daily: 'Media giornaliera', working: 'Media dei giorni lavorativi', unit: 'veicoli al giorno', year: 'Anno di riferimento', unknownYear: 'Anno di riferimento non indicato', missing: 'Non indicato',
    morning: 'Punta mattutina', evening: 'Punta serale', peakNote: 'Il periodo di riferimento delle punte non è specificato. Non sono osservazioni orarie datate.',
    availability: 'Disponibilità secondo la fonte', profile: 'Giorno feriale tipico · veicoli all’ora', period: 'Periodo del rapporto',
    scope: 'Un profilo verificato: Wolhusen Bahnhof, contatore 266. Non copre tutti i contatori lucernesi.',
    discrepancy: 'La mappa indica {map} veicoli/giorno senza anno di riferimento; il rapporto indica {report} per questo periodo. La differenza resta irrisolta.',
    rounded: 'Totali e valori direzionali sono arrotondati separatamente. La loro somma può differire di un veicolo.',
    table: 'Valori orari del profilo', hour: 'Ora', vehicles: 'Veicoli all’ora', source: 'Fonte', acquired: 'Scaricato il',
    loading: 'Caricamento delle statistiche…', error: 'Impossibile caricare le statistiche.', retry: 'Riprova',
    allYear: '365 giorni/anno', threeWeeks: '3 settimane/anno', fiveYears: 'Una volta ogni 5 anni', suspended: 'Sospeso', onRequest: 'Su richiesta', unavailable: 'Non disponibile',
  },
}
