import type {UiLanguage} from '../i18n.ts'
const en = {
 terrainError: 'Terrain unavailable. The combined journey remains on the map.', funicularMap: 'Funicular · continuing on the map', ascent: 'Territet → Rochers-de-Naye', descent: 'Rochers-de-Naye → Territet', loading: 'Loading the summit connection…', unavailable: 'The checked summit connection is unavailable.', retry: 'Retry connection', back: 'Back to the funicular', interchange: 'Change at Glion', first: 'First vehicle', second: 'Second vehicle', minimum: 'Source minimum: 1 minute', scheduled: 'Scheduled connection · no waiting guarantee', access: 'MOB states that the funicular is not accessible to wheelchair or walker users.', path: 'The two Glion stops remain separate. No walking route is shown.', remaining: 'Until departure', evidence: 'Glion connection evidence',
}
export const GLION_COPY: Record<UiLanguage, typeof en> = {en,
 de: {terrainError: 'Gelände nicht verfügbar. Die kombinierte Fahrt bleibt auf der Karte.', funicularMap: 'Standseilbahn · weiter auf der Karte', ascent: 'Territet → Rochers-de-Naye', descent: 'Rochers-de-Naye → Territet', loading: 'Gipfelanschluss wird geladen…', unavailable: 'Der geprüfte Gipfelanschluss ist nicht verfügbar.', retry: 'Anschluss erneut laden', back: 'Zurück zur Standseilbahn', interchange: 'Umsteigen in Glion', first: 'Erstes Fahrzeug', second: 'Zweites Fahrzeug', minimum: 'Quellminimum: 1 Minute', scheduled: 'Fahrplananschluss · keine Wartegarantie', access: 'Laut MOB ist die Standseilbahn für Rollstuhl- oder Rollatornutzende nicht zugänglich.', path: 'Die beiden Glion-Halte bleiben getrennt. Es wird kein Fussweg dargestellt.', remaining: 'Bis zur Abfahrt', evidence: 'Belege zum Glion-Anschluss'},
 fr: {terrainError: 'Relief indisponible. Le trajet combiné reste sur la carte.', funicularMap: 'Funiculaire · suite sur la carte', ascent: 'Territet → Rochers-de-Naye', descent: 'Rochers-de-Naye → Territet', loading: 'Chargement de la correspondance vers le sommet…', unavailable: 'La correspondance vérifiée vers le sommet est indisponible.', retry: 'Réessayer la correspondance', back: 'Retour au funiculaire', interchange: 'Changer à Glion', first: 'Premier véhicule', second: 'Second véhicule', minimum: 'Minimum de la source : 1 minute', scheduled: 'Correspondance horaire · attente non garantie', access: 'Selon MOB, le funiculaire n’est pas accessible aux personnes en fauteuil roulant ou avec un déambulateur.', path: 'Les deux arrêts de Glion restent distincts. Aucun parcours à pied n’est affiché.', remaining: 'Avant le départ', evidence: 'Sources de la correspondance à Glion'},
 it: {terrainError: 'Terreno non disponibile. Il viaggio combinato resta sulla mappa.', funicularMap: 'Funicolare · continua sulla mappa', ascent: 'Territet → Rochers-de-Naye', descent: 'Rochers-de-Naye → Territet', loading: 'Caricamento della coincidenza per la vetta…', unavailable: 'La coincidenza verificata per la vetta non è disponibile.', retry: 'Riprova la coincidenza', back: 'Torna alla funicolare', interchange: 'Cambio a Glion', first: 'Primo veicolo', second: 'Secondo veicolo', minimum: 'Minimo della fonte: 1 minuto', scheduled: 'Coincidenza da orario · attesa non garantita', access: 'Secondo MOB, la funicolare non è accessibile a persone in sedia a rotelle o con deambulatore.', path: 'Le due fermate di Glion restano separate. Non viene mostrato alcun percorso a piedi.', remaining: 'Alla partenza', evidence: 'Fonti della coincidenza a Glion'},
}
