export const GRAUBUENDEN_COPY = {
  en: {
    scope: "Graubünden · initial regional scope",
    subtitle: "Graubünden and its valleys in motion",
    network: "Graubünden · regional study",
    networkStatus: "Graubünden network status",
    placeholder: "Search Chur, Davos or St. Moritz…",
    unavailable: "Graubünden timetable unavailable",
    modes: "Selected trains, buses and three cableways",
    view: "Graubünden canton",
    model: "Partial canton coverage · inferred paths · ≈ illustrative headway movement, not exact departures",
  },
  de: {
    scope: "Graubünden · erste regionale Auswahl",
    subtitle: "Graubünden und seine Täler in Bewegung",
    network: "Graubünden · Regionalstudie",
    networkStatus: "Netzstatus Graubünden",
    placeholder: "Chur, Davos oder St. Moritz suchen…",
    unavailable: "Fahrplan Graubünden nicht verfügbar",
    modes: "Ausgewählte Züge, Busse und drei Seilbahnen",
    view: "Kanton Graubünden",
    model: "Teilabdeckung des Kantons · abgeleitete Wege · ≈ Taktmodell, keine exakten Abfahrten",
  },
  fr: {
    scope: "Grisons · première sélection régionale",
    subtitle: "Les Grisons et leurs vallées en mouvement",
    network: "Grisons · étude régionale",
    networkStatus: "État du réseau des Grisons",
    placeholder: "Rechercher Coire, Davos ou St-Moritz…",
    unavailable: "Horaire des Grisons indisponible",
    modes: "Sélection de trains, bus et trois téléphériques",
    view: "Canton des Grisons",
    model: "Couverture partielle · tracés déduits · ≈ mouvement illustratif à intervalles, départs non exacts",
  },
  it: {
    scope: "Grigioni · prima selezione regionale",
    subtitle: "I Grigioni e le loro valli in movimento",
    network: "Grigioni · studio regionale",
    networkStatus: "Stato della rete dei Grigioni",
    placeholder: "Cerca Coira, Davos o St. Moritz…",
    unavailable: "Orario dei Grigioni non disponibile",
    modes: "Treni, autobus e tre funivie selezionati",
    view: "Cantone dei Grigioni",
    model: "Copertura parziale · percorsi dedotti · ≈ movimento illustrativo a intervalli, partenze non esatte",
  },
} as const
