export const GRAUBUENDEN_COPY = {
  en: {
    scope: "Graubünden · initial rail and bus scope",
    subtitle: "Graubünden and its valleys in motion",
    network: "Graubünden · rail and bus",
    networkStatus: "Graubünden network status",
    placeholder: "Search Chur, Davos or St. Moritz…",
    unavailable: "Graubünden timetable unavailable",
    modes: "Selected complete rail and bus journeys",
    view: "Graubünden canton",
    model: "Partial canton coverage · timetable interpolation on inferred paths",
  },
  de: {
    scope: "Graubünden · erste Bahn- und Busauswahl",
    subtitle: "Graubünden und seine Täler in Bewegung",
    network: "Graubünden · Bahn und Bus",
    networkStatus: "Netzstatus Graubünden",
    placeholder: "Chur, Davos oder St. Moritz suchen…",
    unavailable: "Fahrplan Graubünden nicht verfügbar",
    modes: "Ausgewählte vollständige Bahn- und Busfahrten",
    view: "Kanton Graubünden",
    model: "Teilabdeckung des Kantons · Fahrplaninterpolation auf abgeleiteten Wegen",
  },
  fr: {
    scope: "Grisons · première sélection de trains et bus",
    subtitle: "Les Grisons et leurs vallées en mouvement",
    network: "Grisons · trains et bus",
    networkStatus: "État du réseau des Grisons",
    placeholder: "Rechercher Coire, Davos ou St-Moritz…",
    unavailable: "Horaire des Grisons indisponible",
    modes: "Une sélection de trajets ferroviaires et de bus complets",
    view: "Canton des Grisons",
    model: "Couverture partielle du canton · interpolation horaire sur des tracés déduits",
  },
  it: {
    scope: "Grigioni · prima selezione di treni e autobus",
    subtitle: "I Grigioni e le loro valli in movimento",
    network: "Grigioni · treni e autobus",
    networkStatus: "Stato della rete dei Grigioni",
    placeholder: "Cerca Coira, Davos o St. Moritz…",
    unavailable: "Orario dei Grigioni non disponibile",
    modes: "Viaggi completi selezionati in treno e autobus",
    view: "Cantone dei Grigioni",
    model: "Copertura parziale del cantone · interpolazione oraria su percorsi dedotti",
  },
} as const
