import type { UiLanguage } from '../i18n.ts'
const en = {
  guide: 'Three approaches to Jungfraujoch', intro: 'Select a station to explore its services. The routes meet at Eigergletscher before the final railway section to Jungfraujoch.',
  wengen: 'Via Lauterbrunnen & Wengen', grindelwald: 'Via Grindelwald & Kleine Scheidegg', eiger: 'Via Eiger Express', schematic: 'Approach guide · not to scale',
  rail: 'BOB → Wengernalpbahn → Jungfraubahn', cable: 'BOB → Eiger Express → Jungfraubahn',
  guideNote: 'Changes between services are required. The cableway and railway use shared timetable stops at Terminal and Eigergletscher, with distinct mapped endpoints. No walking path or guaranteed connection is implied.',
  title: 'Interlaken → Jungfraujoch', start: 'Follow the ascent via Wengen', departure: 'Choose a departure', scheduled: 'Dated timetable · via Lauterbrunnen and Wengen',
  change: 'Change at', minutes: 'min', before: 'Before departure', complete: 'Arrived at Jungfraujoch', replay: 'Replay ascent', close: 'Close guide', exit: 'Leave ascent',
  sources: 'Timetable and boarding notes', unavailable: 'This dated ascent is unavailable.', guideUnavailable: 'This approach is unavailable in the loaded timetable.',
  note: 'Scheduled illustration. Connection and seat availability are not guaranteed.',
  lauterbrunnen: 'Lauterbrunnen: no internal GTFS transfer minimum. This composition allows at least 10 minutes.',
  scheidegg: 'Kleine Scheidegg: 3-minute GTFS transfer minimum, plus 10 minutes for the operator’s advance boarding guidance.',
  booking: 'Reservation and boarding rules apply. Check the operator’s current guidance before travel.', operator: 'Operator guidance', model: '2D map · no terrain or tunnel heights. Waiting stages stay at the station; walking is not animated.',
}
export const JUNGFRAU_JOURNEY_COPY: Record<UiLanguage, typeof en> = {
 en,
 de: { guide: 'Drei Wege zum Jungfraujoch', intro: 'Eine Station wählen, um ihre Verbindungen zu entdecken. Die Wege treffen sich am Eigergletscher vor der letzten Bahnstrecke zum Jungfraujoch.', wengen: 'Via Lauterbrunnen & Wengen', grindelwald: 'Via Grindelwald & Kleine Scheidegg', eiger: 'Via Eiger Express', schematic: 'Zugangsübersicht · nicht massstäblich', rail: 'BOB → Wengernalpbahn → Jungfraubahn', cable: 'BOB → Eiger Express → Jungfraubahn', guideNote: 'Umsteigen ist erforderlich. Seilbahn und Bahn nutzen gemeinsame Fahrplanhaltestellen am Terminal und Eigergletscher, aber unterschiedliche kartierte Endpunkte. Gehwege und Anschlüsse sind nicht garantiert.', title: 'Interlaken → Jungfraujoch', start: 'Aufstieg via Wengen folgen', departure: 'Abfahrt wählen', scheduled: 'Datierter Fahrplan · via Lauterbrunnen und Wengen', change: 'Umsteigen in', minutes: 'Min.', before: 'Vor der Abfahrt', complete: 'Am Jungfraujoch angekommen', replay: 'Aufstieg wiederholen', close: 'Übersicht schliessen', exit: 'Aufstieg verlassen', sources: 'Fahrplan und Einstieg', unavailable: 'Dieser datierte Aufstieg ist nicht verfügbar.', guideUnavailable: 'Dieser Zugang ist im geladenen Fahrplan nicht verfügbar.', note: 'Fahrplanillustration. Anschluss und Sitzplatz sind nicht garantiert.', lauterbrunnen: 'Lauterbrunnen: keine interne GTFS-Mindestumsteigezeit. Diese Zusammenstellung lässt mindestens 10 Minuten.', scheidegg: 'Kleine Scheidegg: 3 Minuten GTFS-Mindestumsteigezeit plus 10 Minuten für den vom Betreiber verlangten frühzeitigen Einstieg.', booking: 'Reservations- und Einstiegsregeln gelten. Vor der Reise die aktuellen Betreiberhinweise prüfen.', operator: 'Betreiberhinweise', model: '2D-Karte · keine Gelände- oder Tunnelhöhen. Wartephasen bleiben an der Station; Gehwege werden nicht animiert.' },
 fr: { guide: 'Trois accès au Jungfraujoch', intro: 'Choisissez une gare pour explorer ses services. Les itinéraires se rejoignent à Eigergletscher avant le dernier tronçon ferroviaire vers le Jungfraujoch.', wengen: 'Via Lauterbrunnen et Wengen', grindelwald: 'Via Grindelwald et Kleine Scheidegg', eiger: 'Via Eiger Express', schematic: 'Schéma des accès · pas à l’échelle', rail: 'BOB → Wengernalpbahn → Jungfraubahn', cable: 'BOB → Eiger Express → Jungfraubahn', guideNote: 'Des changements sont nécessaires. Le téléphérique et le train partagent des arrêts horaires à Terminal et Eigergletscher, avec des extrémités cartographiées distinctes. Aucun chemin piéton ni correspondance garantie n’est déduit.', title: 'Interlaken → Jungfraujoch', start: 'Suivre la montée via Wengen', departure: 'Choisir un départ', scheduled: 'Horaire daté · via Lauterbrunnen et Wengen', change: 'Changer à', minutes: 'min', before: 'Avant le départ', complete: 'Arrivée au Jungfraujoch', replay: 'Rejouer la montée', close: 'Fermer le guide', exit: 'Quitter la montée', sources: 'Horaire et embarquement', unavailable: 'Cette montée datée est indisponible.', guideUnavailable: 'Cet accès est indisponible dans l’horaire chargé.', note: 'Illustration de l’horaire. Correspondance et place assise non garanties.', lauterbrunnen: 'Lauterbrunnen : aucun minimum de correspondance interne GTFS. Cette composition prévoit au moins 10 minutes.', scheidegg: 'Kleine Scheidegg : minimum GTFS de 3 minutes, plus 10 minutes pour l’embarquement anticipé demandé par l’exploitant.', booking: 'Les règles de réservation et d’embarquement s’appliquent. Consultez les indications actuelles de l’exploitant avant le voyage.', operator: 'Indications de l’exploitant', model: 'Carte 2D · sans relief ni hauteur des tunnels. Les attentes restent en gare ; la marche n’est pas animée.' },
 it: { guide: 'Tre accessi allo Jungfraujoch', intro: 'Seleziona una stazione per esplorarne i servizi. I percorsi si incontrano a Eigergletscher prima dell’ultimo tratto ferroviario verso lo Jungfraujoch.', wengen: 'Via Lauterbrunnen e Wengen', grindelwald: 'Via Grindelwald e Kleine Scheidegg', eiger: 'Via Eiger Express', schematic: 'Schema degli accessi · non in scala', rail: 'BOB → Wengernalpbahn → Jungfraubahn', cable: 'BOB → Eiger Express → Jungfraubahn', guideNote: 'Sono necessari cambi. Funivia e ferrovia condividono fermate nell’orario a Terminal e Eigergletscher, con estremità cartografate distinte. Nessun percorso pedonale o coincidenza garantita è implicito.', title: 'Interlaken → Jungfraujoch', start: 'Segui la salita via Wengen', departure: 'Scegli una partenza', scheduled: 'Orario datato · via Lauterbrunnen e Wengen', change: 'Cambio a', minutes: 'min', before: 'Prima della partenza', complete: 'Arrivo allo Jungfraujoch', replay: 'Ripeti la salita', close: 'Chiudi la guida', exit: 'Esci dalla salita', sources: 'Orario e imbarco', unavailable: 'Questa salita datata non è disponibile.', guideUnavailable: 'Questo accesso non è disponibile nell’orario caricato.', note: 'Illustrazione dell’orario. Coincidenza e posto a sedere non garantiti.', lauterbrunnen: 'Lauterbrunnen: nessun tempo minimo interno GTFS. Questa composizione prevede almeno 10 minuti.', scheidegg: 'Kleine Scheidegg: minimo GTFS di 3 minuti, più 10 minuti per l’imbarco anticipato richiesto dall’operatore.', booking: 'Si applicano le regole di prenotazione e imbarco. Consulta le indicazioni attuali dell’operatore prima del viaggio.', operator: 'Indicazioni dell’operatore', model: 'Mappa 2D · senza terreno o quote dei tunnel. Le attese restano in stazione; i percorsi a piedi non sono animati.' },
}
