import type { UiLanguage } from '../i18n.ts'
const en = {
 details: 'Journey details', show: 'Follow in measured terrain', hide: 'Return to map', loading: 'Loading measured landscape…', error: 'Terrain unavailable. The ascent remains on the map.', retry: 'Retry terrain',
 outdoor: 'Measured landscape · mapped rail elevation', tunnel: 'Tunnel · continuing on the map', covered: 'Covered section · continuing on the map', alignment: 'Alignment uncertainty · continuing on the map', wait: 'Station stage · terrain resumes outdoors',
 model: 'Landscape and rail heights from swisstopo, shown at equal horizontal and vertical scale. The terrain grid is simplified to about {spacing} m. The train marker is enlarged; its movement is interpolated from the timetable. Tunnels, covered structures and uncertain alignments stay on the map.',
 sources: 'Terrain evidence', elevation: 'Mapped rail elevation',
}
const COPY: Record<UiLanguage,typeof en> = {
 en,
 de: { details:'Reisedetails', show:'Im gemessenen Gelände folgen',hide:'Zur Karte zurück',loading:'Gemessenes Gelände wird geladen…',error:'Gelände nicht verfügbar. Der Aufstieg bleibt auf der Karte.',retry:'Gelände erneut laden',outdoor:'Gemessenes Gelände · kartierte Schienenhöhe',tunnel:'Tunnel · weiter auf der Karte',covered:'Überdeckter Abschnitt · weiter auf der Karte',alignment:'Unsichere Trasse · weiter auf der Karte',wait:'Stationsphase · Gelände folgt im Freien',model:'Gelände- und Schienenhöhen von swisstopo, horizontal und vertikal im gleichen Massstab. Das Gelände ist auf etwa {spacing} m vereinfacht. Der Zugmarker ist vergrössert; seine Bewegung wird aus dem Fahrplan interpoliert. Tunnel, überdeckte Abschnitte und unsichere Trassen bleiben auf der Karte.',sources:'Geländebelege',elevation:'Kartierte Schienenhöhe' },
 fr: { details:'Détails du trajet', show:'Suivre dans le relief mesuré',hide:'Revenir à la carte',loading:'Chargement du relief mesuré…',error:'Relief indisponible. La montée reste sur la carte.',retry:'Réessayer le relief',outdoor:'Relief mesuré · altitude ferroviaire cartographiée',tunnel:'Tunnel · suite sur la carte',covered:'Tronçon couvert · suite sur la carte',alignment:'Tracé incertain · suite sur la carte',wait:'Étape en gare · relief au prochain tronçon extérieur',model:'Altitudes du terrain et de la voie de swisstopo, à la même échelle horizontale et verticale. La grille du relief est simplifiée à environ {spacing} m. Le marqueur du train est agrandi ; son mouvement est interpolé selon l’horaire. Tunnels, ouvrages couverts et tracés incertains restent sur la carte.',sources:'Sources du relief',elevation:'Altitude ferroviaire cartographiée' },
 it: { details:'Dettagli del viaggio', show:'Segui nel terreno misurato',hide:'Torna alla mappa',loading:'Caricamento del terreno misurato…',error:'Terreno non disponibile. La salita resta sulla mappa.',retry:'Riprova il terreno',outdoor:'Terreno misurato · quota ferroviaria cartografata',tunnel:'Galleria · continua sulla mappa',covered:'Tratto coperto · continua sulla mappa',alignment:'Tracciato incerto · continua sulla mappa',wait:'Sosta in stazione · terreno al prossimo tratto aperto',model:'Quote del terreno e della ferrovia di swisstopo, alla stessa scala orizzontale e verticale. La griglia del terreno è semplificata a circa {spacing} m. Il marcatore del treno è ingrandito; il movimento è interpolato dall’orario. Gallerie, strutture coperte e tracciati incerti restano sulla mappa.',sources:'Fonti del terreno',elevation:'Quota ferroviaria cartografata' },
}

export const measuredTerrainCopy = (language: UiLanguage, spacing: number) => ({...COPY[language], model:COPY[language].model.replace('{spacing}',String(spacing))})
