import type { UiLanguage } from '../i18n.ts'

export const ORBITAL_COPY = {
  en: {
  "pageTitle": "All Switzerland · Gleislicht",
  "pageDescription": "An orbital map of Switzerland showing moving public transport services",
  "failed": "The orbital view couldn’t start",
  "failedRestored": "The orbital renderer couldn’t start. Your atlas has been restored.",
  "webglHelp": "Try reloading in a browser with WebGL enabled.",
  "webglRequired": "This experiment needs WebGL.",
  "returnAtlas": "Return to the atlas",
  "loadFailed": "We couldn’t load this part of the day.",
  "dataError": "The map data could not be loaded. Please try again.",
  "movementError": "The movement data could not be loaded or verified. Please try again.",
  "fineError": "Fine terrain couldn’t load. Try again.",
  "retry": "Try again",
  "snowCover": "Simulated snow cover",
  "snow": "Snow",
  "snowline": "Snowline",
  "snowlineAltitude": "Snowline altitude",
  "metresAboveSea": "{height} metres above sea level",
  "simulatedCover": "Simulated cover",
  "viewControls": "View controls",
  "mountainDetail": "Mountain detail",
  "standard": "Standard · ~500 m",
  "fine": "Fine · ~170 m",
  "loadingFine": "Loading fine terrain…",
  "sunlight": "Sunlight",
  "sunPosition": "{altitude}° above horizon · {azimuth}° bearing",
  "sunBelow": "Sun below horizon",
  "drift": "Drift",
  "returnOrbit": "Return to orbit",
  "hideControls": "Hide controls (F)",
  "focusView": "Focus view",
  "about": "About this view",
  "transportTypes": "Transport types",
  "show": "Show {mode}",
  "hide": "Hide {mode}",
  "rail": "Rail",
  "boat": "Boat",
  "speed": "Speed",
  "trails": "Trails",
  "trailDuration": "Trail duration",
  "experiment": "Orbital experiment / 01",
  "country": "All Switzerland",
  "inMotion": "in motion.",
  "subtitle": "One country. Every available connection.",
  "visibleServices": "visible services",
  "activeServices": "active services",
  "preparing": "Preparing orbit",
  "altitudeHelp": "Approximate height above sea level, calculated from the scene’s vertical scale with the 4.5× terrain exaggeration removed.",
  "cameraAltitude": "Camera altitude",
  "cameraAltitudeSea": "Camera altitude above sea level",
  "altitudeValue": "≈ {height} km ASL",
  "gathering": "Gathering the country’s movements…",
  "journeysDay": "{count} journeys across the day",
  "networks": "National rail, PostBus and regional networks",
  "closeAbout": "Close about this view",
  "aboutTitle": "A country made of journeys",
  "aboutJourneys": "{journeys} distinct journey representations from {studies} public studies. Shared services appear once, using their longest available journey.",
  "aboutTimetable": "A composite weekday from 4 and 8 September 2026. These are timetable movements, not live positions. Cableways and other frequency services include representative departures.",
  "aboutTerrain": "Real swisstopo terrain at roughly {spacing}-metre spacing, shown with 4.5× vertical exaggeration. Lake surfaces use approximate terrain-derived levels and stylised moonlight. Lights follow the ground surface, fading out through mapped rail tunnels and back in at their exits. Tunnel passages are approximate matches to OpenStreetMap; coarse Simplon and Gotthard summit paths use projected portal positions. Bridge and cable heights are not surveyed here. Paths follow the source study’s geometry, simplified for this distant view. Unmatched sections retain timetable interpolation. Coverage includes only the available public feeds.",
  "aboutSnow": "The adjustable snowline is simulated cover, using ground elevation with a soft boundary and less accumulation on steep slopes. It does not represent observed snow, glaciers or a weather forecast.",
  "aboutSun": "Optional sunlight follows an approximate astronomical sun position for 8 September 2026, using Swiss local time (CEST) at the centre of Switzerland. Warmth and twilight are illustrative clear-sky lighting. Terrain shadows inherit the 4.5× exaggerated relief; weather, atmospheric refraction and local horizon corrections are not modelled.",
  "dataCredit": "Data: opentransportdata.swiss, FOT, ZVV, TPG/SITG and regional publishers;",
  "lakeCredit": "FOEN lakes",
  "sources": "Sources and methodology",
  "weekday": "Composite weekday · Swiss local time",
  "playbackTime": "Playback time",
  "pause": "Pause",
  "play": "Play",
  "pausePlayback": "Pause playback",
  "playPlayback": "Play playback",
  "focus": "Focus",
  "controls": "Controls",
  "dragHint": "Drag to explore · scroll to descend",
  "closeControls": "Close controls",
  "done": "Done",
  "touchOrbit": "One finger to orbit · pinch to zoom",
  "touchPan": "Two fingers to pan · tap a city to name it",
  "transport": "Transport",
  "playback": "Playback",
  "exitFocus": "Exit focus mode",
  "showControlsHint": "Show controls (Esc)",
  "showControls": "Show controls"
},
  de: {
  "pageTitle": "Die ganze Schweiz · Gleislicht",
  "pageDescription": "Eine Orbitalansicht der Schweiz mit öffentlichen Verkehrsmitteln in Bewegung",
  "failed": "Die Orbitalansicht konnte nicht gestartet werden",
  "failedRestored": "Die Orbitalansicht konnte nicht gestartet werden. Der Atlas wurde wiederhergestellt.",
  "webglHelp": "Bitte in einem Browser mit aktiviertem WebGL neu laden.",
  "webglRequired": "Dieses Experiment benötigt WebGL.",
  "returnAtlas": "Zurück zum Atlas",
  "loadFailed": "Dieser Tagesabschnitt konnte nicht geladen werden.",
  "dataError": "Die Kartendaten konnten nicht geladen werden. Bitte erneut versuchen.",
  "movementError": "Die Bewegungsdaten konnten nicht geladen oder geprüft werden. Bitte erneut versuchen.",
  "fineError": "Das feine Gelände konnte nicht geladen werden. Erneut versuchen.",
  "retry": "Erneut versuchen",
  "snowCover": "Simulierte Schneedecke",
  "snow": "Schnee",
  "snowline": "Schneegrenze",
  "snowlineAltitude": "Höhe der Schneegrenze",
  "metresAboveSea": "{height} Meter über Meer",
  "simulatedCover": "Simulierte Bedeckung",
  "viewControls": "Ansichtssteuerung",
  "mountainDetail": "Geländedetail",
  "standard": "Standard · ~500 m",
  "fine": "Fein · ~170 m",
  "loadingFine": "Feines Gelände wird geladen…",
  "sunlight": "Sonnenlicht",
  "sunPosition": "{altitude}° über dem Horizont · {azimuth}° Richtung",
  "sunBelow": "Sonne unter dem Horizont",
  "drift": "Kamerafahrt",
  "returnOrbit": "Zurück zur Umlaufbahn",
  "hideControls": "Steuerung ausblenden (F)",
  "focusView": "Fokusansicht",
  "about": "Über diese Ansicht",
  "transportTypes": "Verkehrsmittel",
  "show": "{mode} anzeigen",
  "hide": "{mode} ausblenden",
  "rail": "Bahn",
  "boat": "Schiff",
  "speed": "Tempo",
  "trails": "Spuren",
  "trailDuration": "Spurdauer",
  "experiment": "Orbitalexperiment / 01",
  "country": "Die ganze Schweiz",
  "inMotion": "in Bewegung.",
  "subtitle": "Ein Land. Alle verfügbaren Verbindungen.",
  "visibleServices": "sichtbare Verbindungen",
  "activeServices": "aktive Verbindungen",
  "preparing": "Orbitalansicht wird vorbereitet",
  "altitudeHelp": "Ungefähre Höhe über Meer, aus der vertikalen Skala der Szene berechnet und um die 4,5-fache Geländeüberhöhung korrigiert.",
  "cameraAltitude": "Kamerahöhe",
  "cameraAltitudeSea": "Kamerahöhe über Meer",
  "altitudeValue": "≈ {height} km ü. M.",
  "gathering": "Die Bewegungen des Landes werden geladen…",
  "journeysDay": "{count} Fahrten über den Tag",
  "networks": "Nationale Bahn, PostAuto und Regionalnetze",
  "closeAbout": "Informationen zu dieser Ansicht schliessen",
  "aboutTitle": "Ein Land voller Fahrten",
  "aboutJourneys": "{journeys} verschiedene Fahrtdarstellungen aus {studies} öffentlichen Studien. Mehrfach enthaltene Verbindungen erscheinen einmal mit ihrem längsten verfügbaren Fahrtverlauf.",
  "aboutTimetable": "Ein zusammengesetzter Werktag aus dem 4. und 8. September 2026. Die Bewegungen folgen Fahrplänen, nicht Live-Positionen. Seilbahnen und andere Taktverkehre enthalten repräsentative Abfahrten.",
  "aboutTerrain": "Reales swisstopo-Gelände mit ungefähr {spacing} Metern Rasterweite und 4,5-facher vertikaler Überhöhung. Seeflächen verwenden aus dem Gelände abgeleitete Näherungswerte und stilisiertes Mondlicht. Die Lichter folgen der Bodenoberfläche, verschwinden in kartierten Bahntunneln und erscheinen an deren Ausgängen wieder. Tunnelverläufe sind näherungsweise OpenStreetMap zugeordnet; grobe Simplon- und Gotthard-Bergstrecken verwenden projizierte Portalpositionen. Brücken- und Seilhöhen werden hier nicht vermessen. Die Wege folgen der für diese Fernansicht vereinfachten Geometrie der Quellstudie. Nicht zugeordnete Abschnitte behalten die Fahrplaninterpolation. Die Abdeckung umfasst nur verfügbare öffentliche Daten.",
  "aboutSnow": "Die einstellbare Schneegrenze simuliert eine Schneedecke anhand der Bodenhöhe, mit weichem Übergang und weniger Schnee an steilen Hängen. Sie stellt weder beobachteten Schnee noch Gletscher oder eine Wettervorhersage dar.",
  "aboutSun": "Das optionale Sonnenlicht folgt einer ungefähren astronomischen Sonnenposition für den 8. September 2026, mit Schweizer Ortszeit (MESZ) in der Landesmitte. Wärme und Dämmerung sind illustrative Beleuchtung bei klarem Himmel. Geländeschatten übernehmen die 4,5-fache Überhöhung; Wetter, atmosphärische Refraktion und lokale Horizontkorrekturen werden nicht modelliert.",
  "dataCredit": "Daten: opentransportdata.swiss, BAV, ZVV, TPG/SITG und regionale Herausgeber;",
  "lakeCredit": "Seen des BAFU",
  "sources": "Quellen und Methodik",
  "weekday": "Zusammengesetzter Werktag · Schweizer Ortszeit",
  "playbackTime": "Wiedergabezeit",
  "pause": "Pause",
  "play": "Abspielen",
  "pausePlayback": "Wiedergabe pausieren",
  "playPlayback": "Wiedergabe starten",
  "focus": "Fokus",
  "controls": "Steuerung",
  "dragHint": "Ziehen zum Erkunden · Scrollen zum Absteigen",
  "closeControls": "Steuerung schliessen",
  "done": "Fertig",
  "touchOrbit": "Ein Finger zum Drehen · zwei Finger zum Zoomen",
  "touchPan": "Zwei Finger zum Verschieben · Stadt antippen für den Namen",
  "transport": "Verkehr",
  "playback": "Wiedergabe",
  "exitFocus": "Fokusansicht verlassen",
  "showControlsHint": "Steuerung anzeigen (Esc)",
  "showControls": "Steuerung anzeigen"
},
  fr: {
  "pageTitle": "Toute la Suisse · Gleislicht",
  "pageDescription": "Une carte orbitale de la Suisse montrant les transports publics en mouvement",
  "failed": "La vue orbitale n’a pas pu démarrer",
  "failedRestored": "La vue orbitale n’a pas pu démarrer. Votre atlas a été rétabli.",
  "webglHelp": "Essayez de recharger la page dans un navigateur où WebGL est activé.",
  "webglRequired": "Cette expérience nécessite WebGL.",
  "returnAtlas": "Retour à l’atlas",
  "loadFailed": "Cette partie de la journée n’a pas pu être chargée.",
  "dataError": "Les données cartographiques n’ont pas pu être chargées. Veuillez réessayer.",
  "movementError": "Les données de déplacement n’ont pas pu être chargées ou vérifiées. Veuillez réessayer.",
  "fineError": "Le terrain détaillé n’a pas pu être chargé. Réessayez.",
  "retry": "Réessayer",
  "snowCover": "Enneigement simulé",
  "snow": "Neige",
  "snowline": "Limite d’enneigement",
  "snowlineAltitude": "Altitude de la limite d’enneigement",
  "metresAboveSea": "{height} mètres au-dessus du niveau de la mer",
  "simulatedCover": "Couverture simulée",
  "viewControls": "Commandes de la vue",
  "mountainDetail": "Détail du relief",
  "standard": "Standard · ~500 m",
  "fine": "Détaillé · ~170 m",
  "loadingFine": "Chargement du terrain détaillé…",
  "sunlight": "Lumière du soleil",
  "sunPosition": "{altitude}° au-dessus de l’horizon · azimut {azimuth}°",
  "sunBelow": "Soleil sous l’horizon",
  "drift": "Rotation",
  "returnOrbit": "Revenir en orbite",
  "hideControls": "Masquer les commandes (F)",
  "focusView": "Vue épurée",
  "about": "À propos de cette vue",
  "transportTypes": "Types de transport",
  "show": "Afficher : {mode}",
  "hide": "Masquer : {mode}",
  "rail": "Trains",
  "boat": "Bateau",
  "speed": "Vitesse",
  "trails": "Traces",
  "trailDuration": "Durée des traces",
  "experiment": "Expérience orbitale / 01",
  "country": "Toute la Suisse",
  "inMotion": "en mouvement.",
  "subtitle": "Un pays. Toutes les liaisons disponibles.",
  "visibleServices": "services visibles",
  "activeServices": "services actifs",
  "preparing": "Préparation de l’orbite",
  "altitudeHelp": "Altitude approximative au-dessus du niveau de la mer, calculée à partir de l’échelle verticale de la scène, sans l’exagération du relief de 4,5×.",
  "cameraAltitude": "Altitude de la caméra",
  "cameraAltitudeSea": "Altitude de la caméra au-dessus du niveau de la mer",
  "altitudeValue": "≈ {height} km d’altitude",
  "gathering": "Chargement des déplacements du pays…",
  "journeysDay": "{count} trajets sur la journée",
  "networks": "Réseau ferroviaire national, CarPostal et réseaux régionaux",
  "closeAbout": "Fermer les informations sur cette vue",
  "aboutTitle": "Un pays fait de trajets",
  "aboutJourneys": "{journeys} représentations distinctes de trajets issues de {studies} études publiques. Les services communs apparaissent une seule fois, avec leur trajet disponible le plus long.",
  "aboutTimetable": "Un jour ouvrable composite constitué des 4 et 8 septembre 2026. Les déplacements suivent les horaires, sans positions en direct. Les téléphériques et autres services cadencés incluent des départs représentatifs.",
  "aboutTerrain": "Relief réel de swisstopo avec un espacement d’environ {spacing} mètres et une exagération verticale de 4,5×. Les lacs utilisent des niveaux approximatifs déduits du terrain et un éclairage lunaire stylisé. Les lumières suivent le sol, s’effacent dans les tunnels ferroviaires cartographiés et réapparaissent aux sorties. Les tunnels sont associés approximativement à OpenStreetMap ; les tracés grossiers du Simplon et de la ligne de faîte du Gothard utilisent des positions projetées des portails. Les hauteurs des ponts et des câbles ne sont pas relevées ici. Les tracés suivent la géométrie de l’étude source, simplifiée pour cette vue lointaine. Les sections non associées conservent l’interpolation horaire. La couverture se limite aux flux publics disponibles.",
  "aboutSnow": "La limite d’enneigement réglable simule une couverture selon l’altitude du sol, avec une transition douce et moins d’accumulation sur les pentes raides. Elle ne représente ni neige observée, ni glaciers, ni prévisions météo.",
  "aboutSun": "La lumière solaire optionnelle suit une position astronomique approximative du soleil pour le 8 septembre 2026, à l’heure locale suisse (CEST) au centre du pays. Les tons chauds et le crépuscule illustrent un ciel dégagé. Les ombres héritent du relief exagéré de 4,5× ; la météo, la réfraction atmosphérique et les corrections de l’horizon local ne sont pas modélisées.",
  "dataCredit": "Données : opentransportdata.swiss, OFT, ZVV, TPG/SITG et éditeurs régionaux ;",
  "lakeCredit": "lacs de l’OFEV",
  "sources": "Sources et méthodologie",
  "weekday": "Jour ouvrable composite · heure locale suisse",
  "playbackTime": "Heure de lecture",
  "pause": "Pause",
  "play": "Lire",
  "pausePlayback": "Mettre la lecture en pause",
  "playPlayback": "Démarrer la lecture",
  "focus": "Vue épurée",
  "controls": "Commandes",
  "dragHint": "Glisser pour explorer · défiler pour descendre",
  "closeControls": "Fermer les commandes",
  "done": "Terminé",
  "touchOrbit": "Un doigt pour tourner · pincer pour zoomer",
  "touchPan": "Deux doigts pour déplacer · toucher une ville pour son nom",
  "transport": "Transports",
  "playback": "Lecture",
  "exitFocus": "Quitter la vue épurée",
  "showControlsHint": "Afficher les commandes (Échap)",
  "showControls": "Afficher les commandes"
},
  it: {
  "pageTitle": "Tutta la Svizzera · Gleislicht",
  "pageDescription": "Una mappa orbitale della Svizzera con i trasporti pubblici in movimento",
  "failed": "Impossibile avviare la vista orbitale",
  "failedRestored": "Impossibile avviare la vista orbitale. L’atlante è stato ripristinato.",
  "webglHelp": "Ricarica la pagina in un browser con WebGL attivo.",
  "webglRequired": "Questo esperimento richiede WebGL.",
  "returnAtlas": "Torna all’atlante",
  "loadFailed": "Impossibile caricare questa parte della giornata.",
  "dataError": "Impossibile caricare i dati della mappa. Riprova.",
  "movementError": "Impossibile caricare o verificare i dati dei movimenti. Riprova.",
  "fineError": "Impossibile caricare il terreno dettagliato. Riprova.",
  "retry": "Riprova",
  "snowCover": "Manto nevoso simulato",
  "snow": "Neve",
  "snowline": "Limite della neve",
  "snowlineAltitude": "Altitudine del limite della neve",
  "metresAboveSea": "{height} metri sul livello del mare",
  "simulatedCover": "Copertura simulata",
  "viewControls": "Controlli della vista",
  "mountainDetail": "Dettaglio del rilievo",
  "standard": "Standard · ~500 m",
  "fine": "Dettagliato · ~170 m",
  "loadingFine": "Caricamento del terreno dettagliato…",
  "sunlight": "Luce solare",
  "sunPosition": "{altitude}° sopra l’orizzonte · azimut {azimuth}°",
  "sunBelow": "Sole sotto l’orizzonte",
  "drift": "Rotazione",
  "returnOrbit": "Torna in orbita",
  "hideControls": "Nascondi controlli (F)",
  "focusView": "Vista essenziale",
  "about": "Informazioni sulla vista",
  "transportTypes": "Tipi di trasporto",
  "show": "Mostra: {mode}",
  "hide": "Nascondi: {mode}",
  "rail": "Treni",
  "boat": "Battello",
  "speed": "Velocità",
  "trails": "Scie",
  "trailDuration": "Durata delle scie",
  "experiment": "Esperimento orbitale / 01",
  "country": "Tutta la Svizzera",
  "inMotion": "in movimento.",
  "subtitle": "Un paese. Tutti i collegamenti disponibili.",
  "visibleServices": "servizi visibili",
  "activeServices": "servizi attivi",
  "preparing": "Preparazione dell’orbita",
  "altitudeHelp": "Altezza approssimativa sul livello del mare, calcolata dalla scala verticale della scena senza l’esagerazione del rilievo di 4,5×.",
  "cameraAltitude": "Altitudine della camera",
  "cameraAltitudeSea": "Altitudine della camera sul livello del mare",
  "altitudeValue": "≈ {height} km s.l.m.",
  "gathering": "Caricamento dei movimenti del paese…",
  "journeysDay": "{count} corse nell’arco della giornata",
  "networks": "Ferrovie nazionali, AutoPostale e reti regionali",
  "closeAbout": "Chiudi informazioni sulla vista",
  "aboutTitle": "Un paese fatto di viaggi",
  "aboutJourneys": "{journeys} rappresentazioni distinte di corse da {studies} studi pubblici. I servizi condivisi appaiono una sola volta, con il percorso disponibile più lungo.",
  "aboutTimetable": "Un giorno feriale composito del 4 e dell’8 settembre 2026. I movimenti seguono gli orari, senza posizioni in tempo reale. Le funivie e gli altri servizi a frequenza includono partenze rappresentative.",
  "aboutTerrain": "Terreno reale swisstopo con una spaziatura di circa {spacing} metri e un’esagerazione verticale di 4,5×. I laghi usano livelli approssimativi ricavati dal terreno e una luce lunare stilizzata. Le luci seguono il suolo, scompaiono nelle gallerie ferroviarie mappate e riappaiono alle uscite. Le gallerie sono associate in modo approssimativo a OpenStreetMap; i tracciati grossolani del Sempione e della linea di valico del San Gottardo usano posizioni proiettate dei portali. Le altezze di ponti e cavi non sono rilevate qui. I percorsi seguono la geometria dello studio di origine, semplificata per questa vista distante. I tratti non associati mantengono l’interpolazione oraria. La copertura comprende solo i dati pubblici disponibili.",
  "aboutSnow": "Il limite regolabile della neve simula una copertura basata sull’altitudine del suolo, con un confine graduale e meno accumulo sui pendii ripidi. Non rappresenta neve osservata, ghiacciai o previsioni meteorologiche.",
  "aboutSun": "La luce solare opzionale segue una posizione astronomica approssimativa del sole per l’8 settembre 2026, con l’ora locale svizzera (CEST) al centro del paese. I toni caldi e il crepuscolo illustrano un cielo sereno. Le ombre seguono il rilievo esagerato di 4,5×; meteo, rifrazione atmosferica e correzioni dell’orizzonte locale non sono modellati.",
  "dataCredit": "Dati: opentransportdata.swiss, UFT, ZVV, TPG/SITG ed editori regionali;",
  "lakeCredit": "laghi dell’UFAM",
  "sources": "Fonti e metodologia",
  "weekday": "Giorno feriale composito · ora locale svizzera",
  "playbackTime": "Ora di riproduzione",
  "pause": "Pausa",
  "play": "Riproduci",
  "pausePlayback": "Metti in pausa",
  "playPlayback": "Avvia riproduzione",
  "focus": "Vista essenziale",
  "controls": "Controlli",
  "dragHint": "Trascina per esplorare · scorri per scendere",
  "closeControls": "Chiudi controlli",
  "done": "Fine",
  "touchOrbit": "Un dito per ruotare · pizzica per ingrandire",
  "touchPan": "Due dita per spostare · tocca una città per il nome",
  "transport": "Trasporti",
  "playback": "Riproduzione",
  "exitFocus": "Esci dalla vista essenziale",
  "showControlsHint": "Mostra controlli (Esc)",
  "showControls": "Mostra controlli"
},
} satisfies Record<UiLanguage, Record<string, string>>

export type OrbitalCopy = typeof ORBITAL_COPY.en
