import type { UiLanguage } from '../i18n.ts'
const en = {
  title: 'A day on lake and mountain', close: 'Close day rhythm', boats: 'Lake boats', vitznau: 'Vitznau railway', arth: 'Arth-Goldau railway', cable: 'Weggis cableway',
  scope: 'All modes · both directions', active: 'underway', quiet: 'Quiet now', next: 'Next departure', ended: 'No later departure in this study', empty: 'No services in this study', boundary: 'End of study window', first: 'Return to first departure',
  note: 'Bands show scheduled journeys, including station stops. Gaps are quiet periods in this dated timetable. Other dates and seasonal closures are not covered.', source: 'Timetable evidence',
}
export const RHYTHM_COPY: Record<UiLanguage, typeof en> = {
  en,
  de: { title: 'Ein Tag am See und Berg', close: 'Tagesrhythmus schließen', boats: 'Schiffe', vitznau: 'Vitznau-Bahn', arth: 'Arth-Goldau-Bahn', cable: 'Weggis-Seilbahn', scope: 'Alle Verkehrsmittel · beide Richtungen', active: 'unterwegs', quiet: 'Derzeit ruhig', next: 'Nächste Abfahrt', ended: 'Keine spätere Abfahrt in dieser Studie', empty: 'Keine Fahrten in dieser Studie', boundary: 'Ende des Studienzeitraums', first: 'Zur ersten Abfahrt zurück', note: 'Bänder zeigen Fahrplanfahrten mit Stationshalten. Lücken sind Ruhezeiten an diesem Fahrplantag. Andere Daten und saisonale Schließungen sind nicht erfasst.', source: 'Fahrplanbelege' },
  fr: { title: 'Une journée entre lac et montagne', close: 'Fermer le rythme du jour', boats: 'Bateaux du lac', vitznau: 'Train de Vitznau', arth: 'Train d’Arth-Goldau', cable: 'Téléphérique de Weggis', scope: 'Tous les modes · deux sens', active: 'en parcours', quiet: 'Calme en ce moment', next: 'Prochain départ', ended: 'Aucun départ ultérieur dans cette étude', empty: 'Aucun service dans cette étude', boundary: 'Fin de la période étudiée', first: 'Revenir au premier départ', note: 'Les bandes représentent les parcours prévus, arrêts compris. Les intervalles sont les périodes calmes de cet horaire daté. Les autres dates et fermetures saisonnières ne sont pas couvertes.', source: 'Sources horaires' },
  it: { title: 'Una giornata tra lago e montagna', close: 'Chiudi il ritmo del giorno', boats: 'Battelli del lago', vitznau: 'Ferrovia di Vitznau', arth: 'Ferrovia di Arth-Goldau', cable: 'Funivia di Weggis', scope: 'Tutti i mezzi · entrambe le direzioni', active: 'in viaggio', quiet: 'Ora tranquillo', next: 'Prossima partenza', ended: 'Nessuna partenza successiva nello studio', empty: 'Nessun servizio nello studio', boundary: 'Fine del periodo studiato', first: 'Torna alla prima partenza', note: 'Le fasce mostrano i viaggi previsti, incluse le soste. Gli intervalli sono periodi tranquilli di questo orario datato. Altre date e chiusure stagionali non sono incluse.', source: 'Fonti degli orari' },
}
