import type { UiLanguage } from '../i18n.ts'
const en = {
  title: 'Explore the Rigi connections', close: 'Close Rigi connections', intro: 'Two railways meet at Rigi Staffel and continue to Rigi Kulm. Select a stop to explore its services on the map.',
  schematic: 'Selected stops · schematic, not to scale', vitznau: 'Vitznau railway', arth: 'Arth-Goldau railway', boats: 'Boats', cable: 'Cableway', walk: 'Walk / interchange',
  calls: 'scheduled services', pier: 'Pier', valley: 'Cableway valley', cableTop: 'Cableway summit', rail: 'Railway',
  note: 'Dashed links indicate changes at Weggis and Kaltbad, not walking routes. Vitznau’s boat and railway share one timetable stop. Lines show connections, not track layouts; intermediate stops are omitted.', source: 'Connection evidence', unavailable: 'Some connections are not supported by this timetable.',
}
export const RIGI_GUIDE_COPY: Record<UiLanguage, typeof en> = {
  en,
  de: { title: 'Rigi-Verbindungen entdecken', close: 'Rigi-Verbindungen schliessen', intro: 'Zwei Bahnen treffen sich in Rigi Staffel und fahren weiter nach Rigi Kulm. Eine Haltestelle wählen, um ihre Verbindungen auf der Karte zu entdecken.', schematic: 'Ausgewählte Haltestellen · nicht massstabsgetreu', vitznau: 'Vitznau-Bahn', arth: 'Arth-Goldau-Bahn', boats: 'Schiffe', cable: 'Luftseilbahn', walk: 'Fussweg / Umstieg', calls: 'Fahrplanfahrten', pier: 'Schiffstation', valley: 'Talstation', cableTop: 'Bergstation', rail: 'Bahn', note: 'Gestrichelte Linien zeigen Umstiege in Weggis und Kaltbad, keine Fusswege. Schiff und Bahn in Vitznau teilen eine Fahrplanhaltestelle. Linien zeigen Verbindungen, keine Gleispläne; Zwischenhalte sind ausgelassen.', source: 'Verbindungsbelege', unavailable: 'Einige Verbindungen werden von diesem Fahrplan nicht belegt.' },
  fr: { title: 'Explorer les correspondances du Rigi', close: 'Fermer les correspondances du Rigi', intro: 'Deux chemins de fer se rejoignent à Rigi Staffel et continuent vers Rigi Kulm. Sélectionnez un arrêt pour explorer ses services sur la carte.', schematic: 'Arrêts sélectionnés · schéma sans échelle', vitznau: 'Train de Vitznau', arth: 'Train d’Arth-Goldau', boats: 'Bateaux', cable: 'Téléphérique', walk: 'Marche / correspondance', calls: 'services prévus', pier: 'Débarcadère', valley: 'Station inférieure', cableTop: 'Station supérieure', rail: 'Train', note: 'Les pointillés indiquent les changements à Weggis et Kaltbad, pas des itinéraires piétons. Bateau et train à Vitznau partagent un arrêt horaire. Les lignes représentent les liaisons, pas les voies ; des arrêts intermédiaires sont omis.', source: 'Sources des correspondances', unavailable: 'Certaines liaisons ne sont pas établies par cet horaire.' },
  it: { title: 'Esplora i collegamenti del Rigi', close: 'Chiudi i collegamenti del Rigi', intro: 'Due ferrovie si incontrano a Rigi Staffel e proseguono verso Rigi Kulm. Seleziona una fermata per esplorare i suoi servizi sulla mappa.', schematic: 'Fermate selezionate · schema non in scala', vitznau: 'Ferrovia di Vitznau', arth: 'Ferrovia di Arth-Goldau', boats: 'Battelli', cable: 'Funivia', walk: 'A piedi / cambio', calls: 'servizi previsti', pier: 'Imbarcadero', valley: 'Stazione a valle', cableTop: 'Stazione a monte', rail: 'Ferrovia', note: 'Le linee tratteggiate indicano cambi a Weggis e Kaltbad, non percorsi a piedi. Battello e ferrovia a Vitznau condividono una fermata dell’orario. Le linee rappresentano collegamenti, non binari; alcune fermate intermedie sono omesse.', source: 'Fonti dei collegamenti', unavailable: 'Alcuni collegamenti non sono confermati da questo orario.' },
}
