import type { UiLanguage } from '../i18n.ts'
import './territet.css'
const en = {
 combined:'Continue to Rochers-de-Naye',combinedModel:'Timetable interpolation · mapped funicular and cogwheel railway',title:'Territet → Glion',select:'Explore Territet–Glion',placeholder:'Territet, Collonge, Glion…',modes:'24 hours · Territet–Glion funicular',loading:'Loading Territet–Glion…',unavailable:'Territet–Glion is unavailable. Retry or choose another study.',model:'Timetable interpolation · mapped 2D funicular',start:'Follow the Territet–Glion funicular',direction:'Direction',ascent:'Territet → Glion',descent:'Glion → Territet',departure:'Choose a departure',exit:'Exit journey',replay:'Replay journey',arrived:'Arrived',before:'Before departure',evidence:'Timetable and route evidence',details:'Journey details',note:'Dated MVR funicular services on the official FOT installation centreline. Collonge is projected onto this source line. Optional terrain uses separately audited measured track and landscape. Vehicle assignment at the passing loop and cable mechanics remain unestablished.',serviceNote:'Glion (funi) and the Rochers railway stop are distinct source places. A connection or walking transfer is not guaranteed by this study.',empty:'No audited complete journey is available.',guide:'Stops on this journey',
}
export const TERRITET_COPY:Record<UiLanguage,typeof en>={en,
 de:{combined:'Weiter nach Rochers-de-Naye',combinedModel:'Fahrplaninterpolation · kartierte Standseil- und Zahnradbahn',title:'Territet → Glion',select:'Territet–Glion entdecken',placeholder:'Territet, Collonge, Glion…',modes:'24 Stunden · Standseilbahn Territet–Glion',loading:'Territet–Glion wird geladen…',unavailable:'Territet–Glion nicht verfügbar. Erneut versuchen oder eine andere Studie wählen.',model:'Fahrplaninterpolation · kartierte 2D-Standseilbahn',start:'Der Standseilbahn Territet–Glion folgen',direction:'Richtung',ascent:'Territet → Glion',descent:'Glion → Territet',departure:'Abfahrt wählen',exit:'Fahrt verlassen',replay:'Fahrt wiederholen',arrived:'Angekommen',before:'Vor der Abfahrt',evidence:'Fahrplan- und Streckenbelege',details:'Fahrtdetails',note:'Datierte MVR-Standseilbahnfahrten auf der offiziellen BAV-Anlagentrasse. Collonge wird auf diese Quelllinie projiziert. Das optionale Gelände verwendet separat geprüfte, gemessene Gleise und Landschaft. Fahrzeugzuordnung an der Ausweichstelle und Seilmechanik bleiben unbelegt.',serviceNote:'Glion (funi) und die Station der Rochers-Bahn bleiben verschiedene Quellorte. Diese Studie garantiert weder Anschluss noch Fussweg.',empty:'Keine geprüfte vollständige Fahrt verfügbar.',guide:'Halte dieser Fahrt'},
 fr:{combined:'Continuer vers les Rochers-de-Naye',combinedModel:'Interpolation horaire · funiculaire et train à crémaillère cartographiés',title:'Territet → Glion',select:'Découvrir Territet–Glion',placeholder:'Territet, Collonge, Glion…',modes:'24 heures · funiculaire Territet–Glion',loading:'Chargement de Territet–Glion…',unavailable:'Territet–Glion indisponible. Réessayez ou choisissez une autre étude.',model:'Interpolation horaire · funiculaire cartographié en 2D',start:'Suivre le funiculaire Territet–Glion',direction:'Direction',ascent:'Territet → Glion',descent:'Glion → Territet',departure:'Choisir un départ',exit:'Quitter le trajet',replay:'Rejouer le trajet',arrived:'Arrivée',before:'Avant le départ',evidence:'Sources des horaires et du tracé',details:'Détails du trajet',note:'Services datés du funiculaire MVR sur le tracé officiel de l’OFT. Collonge est projeté sur cette ligne source. Le relief optionnel utilise des voies et un terrain mesurés et vérifiés séparément. L’attribution des voies d’évitement aux véhicules et la mécanique du câble ne sont pas établies.',serviceNote:'Glion (funi) et l’arrêt du chemin de fer des Rochers restent des lieux sources distincts. Cette étude ne garantit ni correspondance ni parcours à pied.',empty:'Aucun trajet complet vérifié disponible.',guide:'Arrêts de ce trajet'},
 it:{combined:'Prosegui per Rochers-de-Naye',combinedModel:'Interpolazione degli orari · funicolare e cremagliera cartografate',title:'Territet → Glion',select:'Esplora Territet–Glion',placeholder:'Territet, Collonge, Glion…',modes:'24 ore · funicolare Territet–Glion',loading:'Caricamento di Territet–Glion…',unavailable:'Territet–Glion non disponibile. Riprova o scegli un altro studio.',model:'Interpolazione degli orari · funicolare cartografata in 2D',start:'Segui la funicolare Territet–Glion',direction:'Direzione',ascent:'Territet → Glion',descent:'Glion → Territet',departure:'Scegli una partenza',exit:'Esci dal viaggio',replay:'Ripeti il viaggio',arrived:'Arrivo',before:'Prima della partenza',evidence:'Fonti degli orari e del tracciato',details:'Dettagli del viaggio',note:'Servizi datati della funicolare MVR sul tracciato ufficiale dell’UFT. Collonge è proiettata su questa linea. Il terreno opzionale usa binari e paesaggio misurati e verificati separatamente. L’assegnazione dei binari di incrocio ai veicoli e la meccanica del cavo non sono stabilite.',serviceNote:'Glion (funi) e la fermata della ferrovia dei Rochers restano luoghi distinti nella fonte. Lo studio non garantisce coincidenze o percorsi a piedi.',empty:'Nessun viaggio completo verificato disponibile.',guide:'Fermate di questo viaggio'},
}
