import type { UiLanguage } from '../i18n.ts'
import { measuredTerrainCopy } from './measured-terrain-copy.ts'
const extra = {
 en: { error: 'Terrain unavailable. The journey remains on the map.', alignment: 'Passing loop · continuing on the map', clearance: 'Rail and ground heights differ · continuing on the map', model: 'Measured landscape and rail heights from swisstopo, shown at equal horizontal and vertical scale on a 5 m terrain grid. Both passing-loop branches are shown as context; no branch is assigned to the vehicle. The loop and sections with conflicting rail and ground heights stay on the map. The enlarged vehicle follows its own timetable, without simulating cable mechanics.' },
 de: { error: 'Gelände nicht verfügbar. Die Fahrt bleibt auf der Karte.', alignment: 'Ausweichstelle · weiter auf der Karte', clearance: 'Schienen- und Geländehöhen weichen ab · weiter auf der Karte', model: 'Gemessene Gelände- und Schienenhöhen von swisstopo, horizontal und vertikal im gleichen Massstab auf einem 5-m-Geländeraster. Beide Ausweichgleise dienen als Kontext; dem Fahrzeug wird kein Gleis zugewiesen. Die Ausweichstelle und Abschnitte mit widersprüchlichen Schienen- und Geländehöhen bleiben auf der Karte. Das vergrösserte Fahrzeug folgt seinem eigenen Fahrplan, ohne Simulation der Seilmechanik.' },
 fr: { error: 'Relief indisponible. Le trajet reste sur la carte.', alignment: 'Évitement · suite sur la carte', clearance: 'Altitudes de la voie et du sol différentes · suite sur la carte', model: 'Altitudes mesurées du terrain et de la voie de swisstopo, à la même échelle horizontale et verticale sur une grille de 5 m. Les deux voies d’évitement servent de contexte ; aucune n’est attribuée au véhicule. L’évitement et les tronçons où les altitudes de la voie et du sol divergent restent sur la carte. Le véhicule agrandi suit son propre horaire, sans simulation du câble.' },
 it: { error: 'Terreno non disponibile. Il viaggio resta sulla mappa.', alignment: 'Incrocio · continua sulla mappa', clearance: 'Quote della ferrovia e del terreno diverse · continua sulla mappa', model: 'Quote misurate del terreno e della ferrovia di swisstopo, alla stessa scala orizzontale e verticale su una griglia di 5 m. Entrambi i binari di incrocio sono mostrati come contesto; nessuno è assegnato al veicolo. L’incrocio e i tratti con quote discordanti tra binario e terreno restano sulla mappa. Il veicolo ingrandito segue il proprio orario, senza simulare la meccanica del cavo.' },
}
export const territetTerrainCopy = (language: UiLanguage) => ({...measuredTerrainCopy(language, 5), ...extra[language]})
