import type { UiLanguage } from './i18n.ts'

/** Edition-owned help for the shared desktop tooltip surface. */
export const CONTROL_HELP = {
  "en": {
    "soundOn": "Start music that adapts to the movement",
    "soundOff": "Mute the adaptive soundtrack",
    "soundStarting": "The soundtrack is starting",
    "pulse": "Explore the rhythm of arrivals and departures around the station",
    "tracks": "Show scheduled movements on the station tracks",
    "gridOn": "Show quarter-hour guides around the station clock",
    "gridOff": "Hide the quarter-hour guides",
    "directorOn": "Automatically move between times of day and camera views",
    "directorOff": "Stop the automatic tour and keep the current view",
    "record": "Record and download a 12-second video of the scene",
    "recordStop": "Stop and save the recording",
    "recordSaving": "The recording is being saved",
    "release": "Clear the selection and stop following it to explore freely",
    "corridor": "Follow a journey through the measured terrain",
    "network": "Return to the network map",
    "hubs": "Explore arrivals and departures at a major interchange",
    "isolate": "Focus on this group and dim other services",
    "restore": "Restore all service groups",
    "speed": "Set the playback speed",
    "jump": "Jump to this time of day",
    "airUnavailable": "AIR is available in the national rail study",
    "roadUnavailable": "Road traffic is available in the national morning study"
  },
  "de": {
    "soundOn": "Musik starten, die sich den Bewegungen anpasst",
    "soundOff": "Den adaptiven Soundtrack stummschalten",
    "soundStarting": "Der Soundtrack wird gestartet",
    "pulse": "Den Rhythmus der Ankünfte und Abfahrten am Bahnhof erkunden",
    "tracks": "Geplante Bewegungen auf den Bahnhofsgleisen zeigen",
    "gridOn": "Viertelstunden-Hilfslinien auf der Bahnhofsuhr zeigen",
    "gridOff": "Viertelstunden-Hilfslinien ausblenden",
    "directorOn": "Automatisch zwischen Tageszeiten und Kameraansichten wechseln",
    "directorOff": "Die automatische Tour stoppen und die aktuelle Ansicht behalten",
    "record": "Ein 12-Sekunden-Video der Szene aufnehmen und herunterladen",
    "recordStop": "Aufnahme stoppen und speichern",
    "recordSaving": "Die Aufnahme wird gespeichert",
    "release": "Auswahl und Verfolgung aufheben, um die Karte frei zu erkunden",
    "corridor": "Eine Fahrt durch das vermessene Gelände verfolgen",
    "network": "Zur Netzkarte zurückkehren",
    "hubs": "Ankünfte und Abfahrten an einem grossen Knotenpunkt erkunden",
    "isolate": "Diese Gruppe hervorheben und andere Verkehre abdunkeln",
    "restore": "Alle Verkehrsgruppen wiederherstellen",
    "speed": "Wiedergabegeschwindigkeit einstellen",
    "jump": "Zu dieser Tageszeit springen",
    "airUnavailable": "AIR ist in der nationalen Bahnstudie verfügbar",
    "roadUnavailable": "Strassenverkehr ist in der nationalen Morgenstudie verfügbar"
  },
  "fr": {
    "soundOn": "Lancer une musique qui suit les mouvements",
    "soundOff": "Couper la bande-son adaptative",
    "soundStarting": "La bande-son démarre",
    "pulse": "Explorer le rythme des arrivées et des départs autour de la gare",
    "tracks": "Afficher les mouvements programmés sur les voies de la gare",
    "gridOn": "Afficher les repères de quart d’heure sur l’horloge de la gare",
    "gridOff": "Masquer les repères de quart d’heure",
    "directorOn": "Passer automatiquement entre les heures et les vues de caméra",
    "directorOff": "Arrêter la visite automatique et conserver la vue actuelle",
    "record": "Enregistrer et télécharger une vidéo de 12 secondes de la scène",
    "recordStop": "Arrêter et sauvegarder l’enregistrement",
    "recordSaving": "L’enregistrement est en cours de sauvegarde",
    "release": "Effacer la sélection et arrêter le suivi pour explorer librement",
    "corridor": "Suivre un trajet à travers le relief mesuré",
    "network": "Revenir à la carte du réseau",
    "hubs": "Explorer les arrivées et les départs d’un grand pôle de correspondance",
    "isolate": "Mettre ce groupe en évidence et atténuer les autres services",
    "restore": "Rétablir tous les groupes de services",
    "speed": "Régler la vitesse de lecture",
    "jump": "Passer à cette heure de la journée",
    "airUnavailable": "AIR est disponible dans l’étude ferroviaire nationale",
    "roadUnavailable": "Le trafic routier est disponible dans l’étude nationale du matin"
  },
  "it": {
    "soundOn": "Avviare la musica che si adatta ai movimenti",
    "soundOff": "Disattivare la colonna sonora adattiva",
    "soundStarting": "La colonna sonora si sta avviando",
    "pulse": "Esplorare il ritmo degli arrivi e delle partenze in stazione",
    "tracks": "Mostrare i movimenti programmati sui binari della stazione",
    "gridOn": "Mostrare i riferimenti dei quarti d’ora sull’orologio della stazione",
    "gridOff": "Nascondere i riferimenti dei quarti d’ora",
    "directorOn": "Passare automaticamente tra orari e inquadrature",
    "directorOff": "Fermare il giro automatico e mantenere la vista attuale",
    "record": "Registrare e scaricare un video di 12 secondi della scena",
    "recordStop": "Fermare e salvare la registrazione",
    "recordSaving": "La registrazione viene salvata",
    "release": "Cancellare la selezione e interrompere l’inseguimento per esplorare liberamente",
    "corridor": "Seguire un viaggio attraverso il terreno rilevato",
    "network": "Tornare alla mappa della rete",
    "hubs": "Esplorare arrivi e partenze in un grande nodo di interscambio",
    "isolate": "Evidenziare questo gruppo e attenuare gli altri servizi",
    "restore": "Ripristinare tutti i gruppi di servizi",
    "speed": "Impostare la velocità di riproduzione",
    "jump": "Passare a questo momento della giornata",
    "airUnavailable": "AIR è disponibile nello studio ferroviario nazionale",
    "roadUnavailable": "Il traffico stradale è disponibile nello studio nazionale del mattino"
  }
} satisfies Record<UiLanguage, Record<string, string>>
